### ISSUE TITLE
Unable to set a wallpaper from the app

### ISSUE THREAD

**Issue by Primokorn** [SimpleMobileTools/Simple-Gallery#235] opened 2017-04-24 07:31 UTC
Hi,
On my OnePlus 3T (Android 7.1.2) I have 2 Gallery apps: Simple Gallery and QuickPic (old version before CM acquisition).
From Simple Gallery I can't apply a wallpaper. After pressing the option _Set as Wallpaper_ I have a message saying **_No app capable of it has been found_**.
However, from QuickPic, when I select a picture then _Set as_ I can chose **Simple Wallpaper** to crop, change the aspect ratio and apply the picture as my new wallpaper.

**Comment by tibbi** [comment] 2017-04-24 18:28
Ill release 2.8.7 soon, let me know if it still wont work there

**Comment by Primokorn** [comment] 2017-05-02 09:26
It works well, thanks.

**Comment by KabbAmine** [comment] 2017-05-02 09:59
Same thing here with xiaomi mi4c on nougat  (AICP 12.1).

**Comment by KabbAmine** [comment] 2017-06-21 09:48
I've just tried the 2.10.10 version now and the option is working as expected.

What change(s) fixed the issue? There is nothing related in the last changelogs (And yes, there are people that still read the changelogs :D).

**Comment by tibbi** [comment] 2017-06-21 10:01
heh weird. Then it was probably fixed by detecting the file mimetype simply by its extension, not relying on the MediaMetadataRetriever at https://github.com/SimpleMobileTools/Simple-Commons/commit/c3bca54f5464054ff94911fa6b98e6aa028f8c54 . It was a fix related to the issue happening to some people that if you shared an image at Hangouts or so, it was shared as a video. I couldnt reproduce it just as I couldnt reproduce the wallpaper issue either, but Im glad its fixed :) It wasnt intentional.

**Closed by tibbi** 2017-06-21 10:01 UTC
Labels: bug

**Comment by KabbAmine** [comment] 2017-06-21 10:05
That's the higher level of programming, solving issues unintentionally :D.

Anyway I suggest to not close the issue yet, and wait for op @Primokorn for confirmation.

**Comment by tibbi** [comment] 2017-06-21 10:20
neah, he can reopen it if its still broken

**Comment by Primokorn** [comment] 2017-06-21 11:11
Also fixed on my end 👍
