### ISSUE TITLE
Continuous vertical and horizontal scrolling image viewer

### ISSUE THREAD

**Issue by MilaMurry** [SimpleMobileTools/Simple-Gallery#1792] opened 2020-04-03 02:21 UTC
I have some images with same width but different heights so like to view them like a single long image like most pdf cbs viewers do with no gaps at all between them. I've tried to set the view style to grid then decrease the column to 1 but it just does not work (the images seems to be cropped).

**Comment by tibbi** [comment] 2020-04-03 06:46
if I understand it right, it is a duplicate of #1567

**Closed by tibbi** 2020-04-03 06:46 UTC
