### ISSUE TITLE
Fdroid no longer available

### ISSUE THREAD

**Issue by Monirzadeh** [SimpleMobileTools/Simple-Gallery#1735] opened 2020-02-07 11:22 UTC
Fdroid get this error in description
'The upstream source for this app is no longer available'
Is there any problem
I get pro version on Google play is there any way to get them from fdroid?(maybe I get this error becuse of that)

**Comment by tibbi** [comment] 2020-02-07 11:26
duplicate of #1706

**Closed by tibbi** 2020-02-07 11:26 UTC
