### ISSUE TITLE
Please add TIF/TIFF support

### ISSUE THREAD

**Issue by tcables** [SimpleMobileTools/Simple-Gallery#1781] opened 2020-03-09 22:16 UTC
Hello, thanks for a great app! I appreciate all your hard work.

I'd love to see TIF/TIFF image/document support. A lot of scanned documents are produced in this format, and its been around for a couple decades.

**Comment by tibbi** [comment] 2020-03-09 22:49
duplicate of #663

**Closed by tibbi** 2020-03-09 22:49 UTC
