### ISSUE TITLE
Lag when zooming larger resolution photos

### ISSUE THREAD

**Issue by leonlywong** [SimpleMobileTools/Simple-Gallery#908] opened 2018-08-12 01:08 UTC
Lags when zooming into some of the 17mp photos, some don't lag.
Disable "allow deep zoomable images" fixes it but at the cost of image details.
Thanks.

**Comment by tibbi** [comment] 2018-09-05 14:37
@leonlywong what device do you have? I mean the manufacturer, model, and if you know, the screen density dpi?

**Comment by stelariusinfinitek** [comment] 2018-09-05 18:05
Happens to me too. 

Device : Xiaomi Mi A1
OS : Android 8.1
Simple Gallery version : 4.6.1
Affected image resolution : 12 MP
DPI : 360 (I think. Smallest width in Developer Options)

As @leonlywong said, disabling deep zoom fixes it the lag, but the image quality suffers.

**Comment by tibbi** [comment] 2018-09-05 18:37
if you send me an email at hello@simplemobiletools.com I could send you a test version. There is one thing which might fix it at the cost of slightly reduced image quality.

**Comment by tibbi** [comment] 2018-09-05 22:06
so it should be fixed in 4.6.2, reopen if not

**Comment by leonlywong** [comment] 2018-09-05 23:41
It seems to still lag with photos taken in protrait orientation.

Device : Sony xperia XZ1
OS : Android 8.0
Simple Gallery version : 4.6.2
Affected image resolution : 17 MP
DPI : 424 (from google)

**Comment by tibbi** [comment] 2018-09-06 07:11
but is it better by anything now? Like does it lag less, or at fewer photos? I dont want to reduce the quality too much.

**Comment by leonlywong** [comment] 2018-09-06 10:12
Yes for sure. For photos taken in landscape they are fast. Amount of quality lost is acceptable, although it would be great if it can be further reduced.
However photos taken in portrait orientation is just as lag as before.

**Comment by leonlywong** [comment] 2018-09-09 13:41
Also, I noticed that it lags when swiping between photos taken in portrait orientation, after I wait and let the app load full resolution of those photos.

**Comment by klo2k** [comment] 2018-09-14 12:08
Stumbled across a workaround - in Developer Options, set GPU Renderer to "OpenGL (Skia)".

**Comment by tibbi** [comment] 2018-09-19 21:16
Im working on a workaround, let me know at hello@simplemobiletools.com if you want to test it and I havent sent you an email recently.

**Comment by DaleBCooper** [comment] 2018-11-17 17:47
Zooming on photos taken in portrait orientation is still massively lagging/slow. Zooming on photos taken in landscape orientation works perfectly fast.
Cannot reproduce this on any other gallery app.
Device is an Snapdragon 626 running Oreo 8.1.

**Comment by lufte** [comment] 2019-01-05 17:38
I have the same issue. I'm currently running version 5.1.3 on a Motorola G4 Play. The issue only occurs with photos in portrait orientation.

I've found the following workaround: force landscape orientation (with the button in the to right) and the issue is fixed. You can even switch back to portrait and the issue remains fixed. Otherwise the app becomes quite unusable.

**Comment by tibbi** [comment] 2019-01-05 18:33
well I still couldnt reproduce the issue, not sure why is it happening. Trying it with the latest pro version 6.2.0 from https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro would help too though.

**Comment by lufte** [comment] 2019-01-12 15:12
I hadn't noticed I wasn't getting new updates for my F-Droid installed version. I got the new version from F-Droid (6.2.0) and I can confirm the issue is fixed now.

Thanks for your time!

**Comment by tibbi** [comment] 2019-03-10 09:49
many related things have been improved already, so open a new issue if there are still some problems

**Closed by tibbi** 2019-03-10 09:49 UTC
Labels: bug

**Comment by NineKain** [comment] 2024-09-24 09:00
This still happens to me, Pixel 8a
