### ISSUE TITLE
Images within sub folders of DCIM/Camera do not display.

### ISSUE THREAD

**Issue by greenerk** [SimpleMobileTools/Simple-Gallery#2219] opened 2021-09-10 15:21 UTC
The Gcam (Google Camera) app saves portrait and burst photos within "DCIM_XXX..." folders under DCIM/Camera. e.g. /DCIM/Camera/IMG_20210910_135117/00000PORTRAIT_00000_BURST20210910135117227.jpg

Simple Gallery appears to ignore these as they do not show in app. All other photos under Camera show fine, just nothing saved within a deeper folder.

**Comment by tibbi** [comment] 2021-09-10 16:58
the issue is with the way portrait images are handled, duplicate of #1919 . You can also try enabling "Portrait" at the top Menu -> FIlter.

**Closed by tibbi** 2021-09-10 16:58 UTC
