### ISSUE TITLE
Please change the overview with uncropped previews

### ISSUE THREAD

**Issue by OffifialMITX** [SimpleMobileTools/Simple-Gallery#1447] opened 2019-06-01 04:05 UTC
If you set the columns to minimum, both in vertical and horizontal scrolling, the uncropped preview shows something like
![this](https://i.imgur.com/2HXuBEe.png)
, which is kind of a bummer. I think it would be way more pleasant to use with these settings (and also might be me, but I expected it to me like this), if the images weren't squared but could use the full width of the device, while keeping their aspect ratio and be separated by one pixel line from one another.

_Sent from my Moto E (4) Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by tibbi** [comment] 2019-12-30 21:33
duplicate of #1567

**Closed by tibbi** 2019-12-30 21:33 UTC
Labels: feature request

**Comment by OffifialMITX** [comment] 2019-12-31 06:45
Erm… How is *this* the duplicate if it came almost three months earlier?

**Comment by tibbi** [comment] 2019-12-31 07:45
it has the issue described better, doesnt matter which came earlier
