### ISSUE TITLE
Editing image and exporting it produces low quality image

### ISSUE THREAD

**Issue by tp0** [SimpleMobileTools/Simple-Gallery#1762] opened 2020-02-24 23:11 UTC
Original ([source: Wikipedia](https://upload.wikimedia.org/wikipedia/commons/5/5d/401_Gridlock.jpg)):

![401_Gridlock](https://user-images.githubusercontent.com/5863551/75198976-99ff0b80-576a-11ea-9aef-ad0f9def39e3.jpg)

Edited & exported:

![401_Gridlock_1](https://user-images.githubusercontent.com/5863551/75198982-9cf9fc00-576a-11ea-9cdf-873e2a8eb9aa.jpg)

In the example above I only drew a line with the Brush tool as you can see, but I can reproduce this with all the tools. It looks like as long as the image is altered in anyway and then exported, the low quality image is produced. (Is there a way to export/re-save the image without making any changes?)

Filetype and resolution doesn't seem to matter.

Related and possibly the same bug: #1744 

Android 7.0
Gallery 6.12.5

Definitely a recent regression, but unfortunately I can't be sure about the version.

**Comment by tibbi** [comment] 2020-02-25 07:55
duplicate of #1744

**Closed by tibbi** 2020-02-25 07:55 UTC
