### ISSUE TITLE
Support Material You

### ISSUE THREAD

**Issue by Aurnytoraink** [SimpleMobileTools/Simple-Gallery#2367] opened 2022-02-23 07:59 UTC
As Android 12 introduced Material You, it could be great to see Simple Gallery using it.

**Comment by tibbi** [comment] 2022-02-23 08:35
it affects all apps, so closing it as duplicate of https://github.com/SimpleMobileTools/General-Discussion/issues/180

**Closed by tibbi** 2022-02-23 08:35 UTC
