### ISSUE TITLE
Rounded thumbnails for GIF

### ISSUE THREAD

**Issue by AlbatorV** [SimpleMobileTools/Simple-Gallery#2603] opened 2022-09-07 07:39 UTC
Hi,
Thumbnails for GIF files or folder with GIF inside are not rounded.
![Screenshot_20220907-075718_Gallery](https://user-images.githubusercontent.com/2797485/188818421-f8bb4de6-f19d-40a6-b7ea-8b9a2b33b067.png)
![Screenshot_20220907-075725_Gallery](https://user-images.githubusercontent.com/2797485/188818426-51a7989e-9e47-477c-badb-dec29e4fbe67.png)

**Comment by Aga-C** [comment] 2022-09-07 07:57
It's duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2355.

**Closed** 2022-09-10 21:43 UTC
