### ISSUE TITLE
Delete Exif data?

### ISSUE THREAD

**Issue by frederiiiic** [SimpleMobileTools/Simple-Gallery#1656] opened 2019-12-09 18:21 UTC
Hi there!

I was yesterday trying to delete EXIF Data of a picture and i was suprise to don't find any way to do that on the app. will it ever be available?

Anyway, the app is very easy to use, thanks for the job done!

**Comment by tibbi** [comment] 2019-12-09 21:36
ye, an exif editor is on the roadmap for quite some time now, not sure when will I get to it. Duplicate of #282

**Closed by tibbi** 2019-12-09 21:36 UTC

**Comment by frederiiiic** [comment] 2019-12-09 22:43
Oups sorry for this.

**Comment by puppykickr** [comment] 2019-12-10 19:33
Hey, there is an app on F-Droid, call Scrambled Exif.

It is simple to use, and will scramble the info whenever you share.
