### ISSUE TITLE
UI not responding correctly

### ISSUE THREAD

**Issue by jerryn70** [SimpleMobileTools/Simple-Gallery#245] opened 2017-05-12 11:18 UTC
After sliding 5 to 6 images when I click the image to show navigation bar it won't show the navigation bar. i need to click again to make it visible.

●How to reproduce●

Open a image, click the image to hide navigation bar, then slide to other images. after sliding 5 to 6 images , click the image to make navigation bar visible.  And now what happens It won't respond ,we need to click again to make it visible.

**Comment by Theobald93** [comment] 2017-05-14 09:43
Can confirm this. After 5-10 720x1280 jpg images.

**Comment by tibbi** [comment] 2017-05-14 15:04
I cannot reproduce it like that on Android 6. Isnt the issue that instead of double clicking you just have to wait a bit? Thats what I can reproduce. Even if you swipe just once and click fast, you cannot toggle fullscreen mode. Theres some issue during loading the higher quality image, couldnt fix it nicely and I dont want to add hacks for something like that :p

**Comment by Theobald93** [comment] 2017-05-14 16:23
@tibbi: You are right. It depends not on the count of images but of the waiting time.
Android 7.1.2

**Comment by tibbi** [comment] 2018-10-19 20:30
should be fixed already

**Closed by tibbi** 2018-10-19 20:30 UTC
Labels: bug
