### ISSUE TITLE
Feature request: overwrite picture when editing

### ISSUE THREAD

**Issue by popogomo** [SimpleMobileTools/Simple-Gallery#2824] opened 2023-04-11 23:52 UTC
When we edit a picture and then save ir, the app is asking to create a copy of the file, without overwriting the existing file.

Whilst this is good in some cases, its definitely not so convenient in other cases as we are ending up having 2 version of the picture: the original and modified one.

Can you please add a possibility in app settings to allow to simply overwrite the existing file when saving the changes? In this case users who need it can enable it, and other users who don't need it, can leave it like that.

Thanks!

**Comment by Aga-C** [comment] 2023-04-12 05:36
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2438.

**Closed** 2023-04-12 07:40 UTC
