### ISSUE TITLE
insufficient memory

### ISSUE THREAD

**Issue by maszek** [SimpleMobileTools/Simple-Gallery#535] opened 2017-12-28 14:28 UTC
Hi, I am experiencing problems saving/overwriting image files after rotating them.
Saving them under a new name doesn't help either.
I have my photos stored on a 120GB Sandisk micro SD card, with 85% storage space available. Also, I've cleared memory cache with CCleaner.
My device is a Lenovo K6 (K33a48) running on Android 7.0

**Comment by tibbi** [comment] 2017-12-28 14:44
it means memory as RAM, not storage. It is a duplicate of #400 , Ill try optimizing when I can

**Closed by tibbi** 2017-12-28 14:44 UTC

**Comment by maszek** [comment] 2017-12-30 19:35
Hello Tibor,

 

I suspected as much, that’s why I wrote that my device has plenty of free random access memory (RAM) available (500 x times the amount needed for a photo of about 2 mb).

 

Jan

 

Van: Tibor Kaputa <notifications@github.com>
Beantwoorden - Aan: SimpleMobileTools/Simple-Gallery <reply@reply.github.com>
Datum: donderdag 28 december 2017 om 15:44
Aan: SimpleMobileTools/Simple-Gallery <Simple-Gallery@noreply.github.com>
CC: Regular Rocker <jan@regularrocker.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [SimpleMobileTools/Simple-Gallery] insufficient memory (#535)

 

it means memory as RAM, not storage. It is a duplicate of #400 , Ill try optimizing when I can
