### ISSUE TITLE
Sorting by "date created" doesn't work 

### ISSUE THREAD

**Issue by robson-sz** [SimpleMobileTools/Simple-Gallery#863] opened 2018-07-19 03:46 UTC
Hello! 
I've discovered this app on f-droid yesterday, outstanding job! 
There's only one issue: 
I cannot sort by date created, it stays in the same order as date modified. 
File details shows both dates. 
Other sorting methods work. 
App version: 4.3.3

**Comment by tibbi** [comment] 2018-07-19 07:32
are the files in the same folder where they were created, or have they been copied over from somewhere? It can glitch after copying.

**Comment by robson-sz** [comment] 2018-07-19 07:36
They were synchronised using syncthing.  Gallery app was installed after all them were in place and syncthing was disabled.

**Comment by tibbi** [comment] 2018-07-19 07:41
ye, well it doesnt matter when was the gallery installed, the files dont have correct dates at the device mediastore. I will add some button in the future to fix those dates.

**Comment by robson-sz** [comment] 2018-07-19 07:53
I'm not sure what device mediastore is,  but gallery certainly shows correct dates "last modified" and "date taken" in photo properties. 
"Last modified" for all pictures differs from date when they were written on my phone. It shows correctly date when picture was cropped, brightened etc. 
Date taken also looks correct. 
Still "date taken" are ignored while sorting.

**Comment by tibbi** [comment] 2018-07-19 07:59
ye because if you show a single file Properties, it checks the file exif data to have correct info. But at sorting checking file by file would be really slow, so Im relying on the device mediastore, which is an internal database storing all file metadata for fast querying. So all that needs to be done is manually check file by file and update the info in mediastore. I might add some button for fixing dates in the next version already as you arent the only one with this issue.

**Comment by robson-sz** [comment] 2018-07-19 08:01
Thank you very much for quick and detailed response. 
Looking forward to new functionality:)

**Comment by tibbi** [comment] 2018-07-23 09:30
the files in that folder were copied from somewhere, right?

**Comment by robson-sz** [comment] 2018-07-23 10:58
Like earlier, it's synchronized with other device. Photos have not been modified or copied since last week.

**Comment by chris-w89** [comment] 2018-07-24 14:48
That would be great when the exif data will be used. Looking forward to it :)
By the way amazing app. Thanks @tibbi and all other devs. For supporting I bought the "simple thank you" and made a pull request for translation.

**Comment by tibbi** [comment] 2018-07-25 12:04
@robson-sz if I send you a test version, can you try it out? Ive added a function to manually fix the date of selected photos. It isnt finished yet, I just want to test if the concept itself works. Send me a mail at hello@simplemobiletools.com if you want the test version, it is easier to send it via email. Thanks

**Comment by tibbi** [comment] 2018-08-08 20:57
Ill close this, you can fix the file date_taken by long pressing it and selecting "Fix Date Taken values".

**Closed by tibbi** 2018-08-08 20:57 UTC
Labels: bug

**Comment by licaon-kter** [comment] 2018-10-02 19:53
I would like this fixed too, DateTaken is correct and DateModified can't be fixed (Android limitation), hence all the files are sorted at "date the user copied the files".  I 've see other apps like Sony Album that correctly use DateTaken without any speed penalty.


Could this be reopened...or the "slow scan" implemented as an experimental option?

Thanks

**Comment by tibbi** [comment] 2018-10-02 20:08
I dont want to add that, it would be ridiculously slow. Doesnt selecting the files and pressing "Fix Date Taken values" fix it?

**Comment by licaon-kter** [comment] 2018-10-03 04:53
Fix what exactly? The Taken date is correct say February....the Modified date (when copied on the device) is July...Io run the Fix values thing but nothing happens, and I don't expect anything to actually  happen, the Taken date is correct and the Modified date can't be modified (Android limitation)

**Comment by neekless** [comment] 2018-10-03 05:05
It fixes the date taken value in mediastore with the date taken in exif data. Are you sorting by date taken or date modified?

**Comment by licaon-kter** [comment] 2018-10-03 06:34
@neekless I didn't check the code, but both SortBy and GroupBy DateTaken don't actually work as expected. Files still sorted as DateModified.

The FixDate function poped a toast that it did its thing. I even force-closed the app and clean CACHE data, yet...nothing.

**Comment by tibbi** [comment] 2018-10-03 07:01
I dont understand what is wrong then. Files have proper dates individually, but they are still sorted wrong?

**Comment by licaon-kter** [comment] 2018-10-03 07:38
_DateTaken is correct, files are sorted/grouped by DateModified when you select "sort by DateTaken"._
 But I've said this already in all my posts

**Comment by licaon-kter** [comment] 2018-10-04 06:56
BTW, not sure how, but https://github.com/kollerlukas/Camera-Roll-Android-App shows them ok, by DateTaken, as expected. 🤷

**Comment by tibbi** [comment] 2018-10-04 09:39
well the "Fix Date Taken values" fixed the issue to everyone so far, you are the first one reporting this issue. Ill see if I can improve it in the future.

**Comment by licaon-kter** [comment] 2019-03-13 23:00
@tibbi Still an issue.

How long does "Fix Date Taken values" actually take to do it's thing? I can see the toast at first but then there's no progress indicator.

**Comment by tibbi** [comment] 2019-03-13 23:12
it should be close to instant without a progress indicator, with a message like "Dates fixed successfully", or some fail message. You dont see anything after "Fixing...", even if you select 1 image only? What app version do you have? Are you using the latest version 6.6.0?

**Comment by licaon-kter** [comment] 2019-03-14 06:43
Yes, latest, didn't expect it to finish that fast for >1000 pics though. :)

Also, it doesn't fix anything, still sorted by date modified (aka date I copied the files on the device)

Android 6.0.1

**Comment by tibbi** [comment] 2019-03-14 08:37
There are apparently some glitches happening to some people, but I couldnt reproduce any of the issues so far. Try renaming the file, maybe then fixing date taken, if it helps. Also make sure you are not mistaking Sort by and Group by.

**Comment by licaon-kter** [comment] 2019-03-14 11:12
@tibbi Doesn't matter, Group or Sort, pictures are still sorted by copy date, aka yesterday evening, although Taken Date varies between 2017 and 2018.

**Comment by tibbi** [comment] 2019-03-14 14:18
have you tried renaming a file? My guess is that the file isnt present in the android mediastore and so the fixing wont do anything. So even if you try fixing just 1 file, you still see no success/fail message, only "Fixing.."?

**Comment by licaon-kter** [comment] 2019-05-17 07:09
Renaming... wtf? That actually works... 

Ok, great... Now, how do I rename 10000 files exactly?

I've tried to rename it in another app as a test (thinking that I can just script something fast with Termux) but that doesn't work :(

**Comment by licaon-kter** [comment] 2019-05-17 07:42
So actually not useful, unless you don't mind mangled filename... :( 

Basically unless you do the renaming IN APP, you still have them broken.

So, I did:
* fix date (no change, ALL files are TODAY)
* rename all IN APP, add suffix (fixed, ALL files are sorted by their true date)
* try to remove suffix via Termux, `rename '_fix' ''` (BROKEN again, ALL files are TODAY)

:confounded:
