### ISSUE TITLE
Allow keeping Date Modified at file moving

### ISSUE THREAD

**Issue by gcalzo** [SimpleMobileTools/Simple-Gallery#365] opened 2017-09-17 08:45 UTC
This feature request may be a duplicate of #310 but here I'm talking about **moving** files!

Photo moved get _today's date/time_ even when moved from SD to SD! All gallery I'm testing are keeping file's date/time when moved. To me this is important! _Not a lot_ for photo, since sorting is done using exif, but **essential** for video because they do not have exif info!

**Comment by tibbi** [comment] 2017-09-17 08:51
copy/move would be handled the same way, Ill close it as a duplicate of #310

**Closed by tibbi** 2017-09-17 08:51 UTC
