### ISSUE TITLE
Video Playback pauses when multi tasking

### ISSUE THREAD

**Issue by llucid-97** [SimpleMobileTools/Simple-Gallery#2267] opened 2021-11-19 20:41 UTC
When playing videos in split screen (multi tasking) mode, the app pauses playback if you tap anything on the other screen.
This makes it basically impossible to use while multi tasking.
Would it be possible to (optionally?) have it continue playing regardless?

**Comment by tibbi** [comment] 2021-11-19 20:51
duplicate of #472

**Closed by tibbi** 2021-11-19 20:51 UTC
