### ISSUE TITLE
Set transparent background color separately

### ISSUE THREAD

**Issue by lgq-lzw** [SimpleMobileTools/Simple-Gallery#2325] opened 2021-12-31 09:01 UTC
It is recommended to set the background color of the transparent part of the picture with transparent channel separately instead of using the general background color.

The transparent background color should be set as checkerboard grid, like photoshop, xnview.

**Comment by tibbi** [comment] 2021-12-31 10:00
duplicate of #1301

**Closed by tibbi** 2021-12-31 10:00 UTC
