### ISSUE TITLE
Image editor not working on v6.11.4 (Android 5.1.1)

### ISSUE THREAD

**Issue by Xerren09** [SimpleMobileTools/Simple-Gallery#1688] opened 2019-12-29 15:03 UTC
Opening the editor seemingly opens a new empty black screen what automatically closes, opens up a second time, then returns the gallery with the same initial image opened.

_(Hi from GooglePlay, thanks for answering to my review, i moved this here because that way of communication is rather bad)_

**Comment by tibbi** [comment] 2019-12-29 16:10
Have you moved the app itself on an SD card, or it is installed on the internal storage?

**Comment by Xerren09** [comment] 2019-12-29 21:17
It is installed on the internal storage. 
I've also tried to reset app data and do a clean install, but neither of these caused any change.

**Comment by tibbi** [comment] 2019-12-29 22:03
try if this app works please https://play.google.com/store/apps/details?id=com.photoeditorsdk.android.app . It is the sample app of the used library

**Comment by Xerren09** [comment] 2019-12-30 11:37
It works perfectly, with all functions as far as I tried.
If it is of any help, it seems to me that when i open the built-in editor in Simple Gallery it tries but fails to load the sdk up and then attempts to relaunch itself, but crashes back to the gallery. I can provide video if it helps.

**Comment by tibbi** [comment] 2019-12-30 12:02
Okay, they are using a newer library version, guess the glitch has been fixed there. I didnt want to update yet as Ive found a couple new issues, that I reported. Hopefully they will be fixed soon and I can update too. Thanks for the testing.

**Comment by patrickdrd** [comment] 2020-01-02 10:53
may I ask, what was wrong with the previous image editor?
can you give us a switch to choose the image editor we would like to use?
because I think I liked the previous one more

**Comment by tibbi** [comment] 2020-01-02 11:24
the previous one missed many functions and you could do only 1 operation at once, not crop and image and draw together. It was limited in many ways and improving it would be tons of work, so I just replaced it. There wont be any switch, you will have to use the new one, or get some old app version.

**Comment by eremitein** [comment] 2020-01-03 10:41
Hi!

APP version : 6.11.4 (and also current build from github)
Android : 10

Image Editor not save edited photo too, some from logs:

W ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface

of cause images in .PNG format and previous build worked fine. Which libs did that regression? I want using latest build which have better interface but i don't know how to fix

**Comment by tibbi** [comment] 2020-01-03 11:09
I dont know what you mean here, the app uses the editor version 6.0.10

**Comment by eremitein** [comment] 2020-01-03 11:29
sorry, my bad - i meant version with old editor (app v6.10.8) - it's haven't that bug

**Comment by tibbi** [comment] 2020-01-03 11:31
sure, the editor was a whole different one before that. Anyway, the library version Im using now is 6.6.4, not 6.0.10.

**Comment by eremitein** [comment] 2020-01-03 11:43
[editor_cant_save_png.txt](https://github.com/SimpleMobileTools/Simple-Gallery/files/4018961/editor_cant_save_png.txt)
that's a logs, all what i can send to help you fix bug

**Comment by tibbi** [comment] 2020-01-03 15:31
nothing there is really related to the editor

**Comment by eremitein** [comment] 2020-01-03 18:32
> nothing there is really related to the editor

you Master, you should know your software better))

but i have a fact: Simple Gallery v6.11.0 _not_ saving edited .png file, but v6.10.8 saving

so i did rollback to v6.10.8 and built it with my changes and some your backported commits. until you fix bug with editor i will stay on old stable one version

**Comment by Rikk** [comment] 2020-01-09 19:00
For reference, my discussion about new editor crash is at https://github.com/SimpleMobileTools/Simple-Gallery/commit/83c9bcc46c45ea5000d80f455e6aa9e82a7937c6

**Comment by tibbi** [comment] 2020-02-12 18:34
the editor has been updated, please retry it with 6.12.5 and open a new issue if there is still something wrong. It definitely wont be the same issue.

**Closed by tibbi** 2020-02-12 18:34 UTC
Labels: bug

**Comment by Xerren09** [comment] 2020-02-12 21:32
Just an update to verify the closure: update to v6.12.4 solved the issue, image editor is now correctly working (same environment).

**Comment by Rikk** [comment] 2020-02-12 21:36
True, works for me too :)
