### ISSUE TITLE
Mosaic layout

### ISSUE THREAD

**Issue by Donkey-Doug** [SimpleMobileTools/Simple-Gallery#2731] opened 2023-01-15 23:33 UTC
Consider adding a mossic layout:

![Screenshot_20230116-003229_Trebuchet](https://user-images.githubusercontent.com/50382414/212573563-1f4326f2-9134-433d-acfd-4516a4db242b.png)

![Screenshot_20230116-003308_Trebuchet](https://user-images.githubusercontent.com/50382414/212573570-78512ee3-59c8-4366-900e-004d4bf3f342.png)

**Comment by Aga-C** [comment] 2023-01-16 07:29
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/1567.

**Closed** 2023-01-16 08:27 UTC

**Comment by jcperil** [comment] 2023-01-20 07:51
The padding between the thumbnails are so slick. What is this application?

**Comment by Donkey-Doug** [comment] 2023-01-20 08:07
> The padding between the thumbnails is so slick. What is this application?

Aves Gallery
