### ISSUE TITLE
[feature requets] Less storage usage for thumbnails generation

### ISSUE THREAD

**Issue by KnIfER** [SimpleMobileTools/Simple-Gallery#1503] opened 2019-07-16 08:55 UTC
Nice app series!
However,  SimpleGallery is keeping generating new thumbnails which is taking up phone space when:
- 'Crop thunmbnails' setting is changed
- you reduce or increase column count
- you click on a video to enter SimpleGallery's slideshow mode

I cannot find the folder holding thumbnails, but I am monitoring app storage changes via system settings -> app info.

**Comment by tibbi** [comment] 2019-07-16 10:42
limiting cache size is on the roadmap, I created a new issue about it. Duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/1504

**Closed by tibbi** 2019-07-16 10:42 UTC

**Comment by KnIfER** [comment] 2019-07-16 15:37
It needs optimization as Glide is identically copying the image to the cache directory when you are in the sildeshow mode.  (as the generated thumbnail is big enough and should not be saved to disk)
