### ISSUE TITLE
Moving files changed their modify date/time

### ISSUE THREAD

**Issue by EkriirkE** [SimpleMobileTools/Simple-Gallery#2488] opened 2022-05-29 03:28 UTC
Moving files "touch"es them, so sorting gets screwed up.

**Comment by tibbi** [comment] 2022-05-29 07:07
what app and OS version are you using?

**Comment by EkriirkE** [comment] 2022-05-29 17:12
6.23.8 Pro from F-Droid, Android 11/LineageOS 18
this just started happening with the recent version that removed hidden folders

**Comment by tibbi** [comment] 2022-05-29 17:22
right, sadly we cannot make it work on Android 11 due to some system restrictions, but it works for 12 already

**Comment by EkriirkE** [comment] 2022-05-29 17:24
Ok, so then until my OS catches up to 12 I should downgrade Gallery and not update it until 12 is available for me I guess

**Comment by J4CKED** [comment] 2022-06-04 11:49
Copying and moving photos changes the modification date.
Android 12
v6.23.9

**Comment by tibbi** [comment] 2022-06-04 14:08
does it happen at copying from internal storage to internal storage or how?

**Comment by J4CKED** [comment] 2022-06-04 15:06
- In internal memory, between folders,
- from phone to memory card, 
- from memory card to phone.

**Comment by J4CKED** [comment] 2022-06-06 16:55
Fixed in v6.23.10

**Comment by tibbi** [comment] 2022-06-06 17:04
O.o

**Comment by tibbi** [comment] 2022-06-07 21:05
there were no related changes at all, guess it depends on the files you are testing with

**Comment by J4CKED** [comment] 2022-06-07 21:56
Weird. I'll do some more testing tomorrow and let you know.

**Comment by J4CKED** [comment] 2022-06-08 10:36
I did the tests a while ago.

Version 6.23.10 FOSS copies and transfers correctly from internal memory to memory card and vice versa.

Version 6.23.11 FOSS and proprietary is messed up and changes the date when copying and transferring photos.

As I wrote yesterday. 
I deleted the cache and restarted the phone between installations.

**Comment by cormacltighe** [comment] 2022-06-25 15:23
An update just came out on google play that mentions "moving issues." If this was meant to fix this issue, it didn't fix it for me

**Comment by EkriirkE** [comment] 2022-07-07 18:10
> What do you mean you can't do this? I can open Termux and type `mv` and it works flawlessly

 I rolled back to 6.23.6 and froze updates.

**Comment by h0jeZvgoxFepBQ2C** [comment] 2022-07-28 16:34
Can confirm its not working correctly and changing file times on Android 11 (Lineage 18.1) with latest version 6.23.13.

**Comment by h0jeZvgoxFepBQ2C** [comment] 2022-07-28 17:02
This is actually a duplicate of #2321 as it seems, or am I wrong?

**Comment by tibbi** [comment] 2022-07-28 20:03
ye thanks, duplicate of #2321

**Closed by tibbi** 2022-07-28 20:03 UTC
