### ISSUE TITLE
Feature Request: Tags

### ISSUE THREAD

**Issue by FarukOzderim** [SimpleMobileTools/Simple-Gallery#2227] opened 2021-09-16 08:41 UTC
Hello, I am a user of Simple Gallery Pro.

I would like to ask what do you think of letting tagging of the media. Which would be written to file information, and can be filtered or searched?

**Comment by tibbi** [comment] 2021-09-16 10:16
duplicate of #373

**Closed by tibbi** 2021-09-16 10:16 UTC
