### ISSUE TITLE
Diashow rotate by aspect ratio applied on wrong image 

### ISSUE THREAD

**Issue by chilliger** [SimpleMobileTools/Simple-Gallery#1655] opened 2019-11-30 16:21 UTC
When Diashow shows a vertical image that should be rotated, the rotation is applied on the following image and not on the actual image that needs to be rotated.
Steps to reproduce:
1. Set up rotate full screen media by aspect ratio in the settings 
2. Start Diashow with a vertical image followed by a horizontal image 
-> instead of the vertical image the horizontal one gets rotated

**Comment by tibbi** [comment] 2019-11-30 16:49
you mean slideshow, or what is diashow? It might be a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/1652

**Comment by chilliger** [comment] 2019-11-30 17:26
Slideshow, yes.

**Comment by tibbi** [comment] 2019-11-30 17:48
ok, then it is a duplicate, I plan checking it already

**Closed by tibbi** 2019-11-30 17:48 UTC
