### ISSUE TITLE
High-resolution photos are very slow to pinch-zoom

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Gallery#299] opened 2017-07-05 14:29 UTC
This is probably known by now but I didn't see an issue for it. Even on a fast device like my Moto X Pure, its clear that Simple Gallery doesn't zoom as quickly as the proprietary image viewer. On slower devices like those with a Snapdragon 430 such as my cousin's Xiaomi Redmi 5, it's clear that Simple Gallery will suddenly slow down while pinch-zooming on images over 3000 pixels in height. Pictures over 12 megapixels are noticeably slower to zoom in on. 

Other viewers like Piktures and Quickpic are faster, but of course, they are proprietary. 

I guess the only solution is to find a better open-source image lib, but that probably doesn't exist yet. 

Anybody else noticed the slowdown with high-resolution photos, especially on slower devices?

**Comment by jerryn70** [comment] 2017-07-06 05:46
Yes iam face this pinch to zoom and double tap zoom issue on my snapdragon 620 processor device

**Comment by touzainanboku** [comment] 2017-07-09 19:31
Yep, I can reproduce this on my Xperia Z2.

**Comment by ainola** [comment] 2017-07-31 05:53
This also occurs when swiping between different images.

**Comment by 2SI3NX** [comment] 2017-12-18 23:13
I face the same problem when opening ANY image, i tried to pinch to zoom and it doesnt, i have to double tap it so that the zoom 'activates' then i can zoom.

**Comment by wavexx** [comment] 2018-02-02 15:46
I love Simple-Gallery because it can show the image without adding extra useless stuff on top (contrary to most other galleries I tried on f-droid), but swiping between images, irregardless of resolution, is incredibly frustrating.

I only use the gallery to see the latest few images I took with opencamera, I don't use it for anything else.

Swiping forward sometimes is butter-smooth, but then you try to go back one image and it takes 1/2 seconds with massive stuttering. You flip forward again, and you have a 50/50 change of being either fast or incredibly choppy.

I wouldn't even care about the animation really. All I'd want it to get from the previous/next image _quick_.
I just tried today's update on F-Droid, but the problem is still there.

Any chance there is interest in improving this or should I look at alternatives?

**Comment by tibbi** [comment] 2018-02-02 15:52
Try enabling "Replace deep zoomable images"... in settings if you have version 3.3.1. If you dont need zooming it should work a lot better.

**Comment by wavexx** [comment] 2018-02-02 17:29
Seems *much* better indeed. But the setting itself doesn't tell me much of what it does exactly. Does this enable mipmapping?

**Comment by tibbi** [comment] 2018-02-03 08:33
no, when it is enabled, Im not using the library used for deep zooming which works by subsampling.  I just use the library used for loading casual photos, there I can set argb_8888 quality too so gradient parts look pretty.

**Comment by wavexx** [comment] 2018-02-03 10:17
On Sat, Feb 03 2018, Tibor Kaputa wrote:
> no, when it is enabled, Im not using the library used for deep zooming
> which works by subsampling. I just use the library used for loading
> casual photos, there I can set argb_8888 quality too so gradient parts
> look pretty.

I see. I can still zoom enough for my purposes. Massive performance
difference in my case, every action is now responsive.

**Comment by tibbi** [comment] 2018-02-03 12:34
ye, but some people expect good zoom so that is the default behaviour. I'd obviously like the best of both, its just not that easy.

**Comment by 2SI3NX** [comment] 2018-02-03 13:50
@tibbi i can see a huge improvement in the zooming, however i have noticed some minor detail:
When first opening the photo, as soon as you open the photo you immediately want to zoom and it wont, it will zoom if you touch it again or if you wait for about 1-2 seconds(after opening the photo) and then start zooming.

So you cant immediately zoom as soon as you open the photo.

**Comment by tibbi** [comment] 2018-02-03 14:42
ye that is expected, there are different libraries used for the initial image and the deep zoomable one

**Comment by tibbi** [comment] 2018-10-02 20:28
should be fixed already

**Closed by tibbi** 2018-10-02 20:28 UTC
Labels: bug
