### ISSUE TITLE
Crash for folder with .nomedia file

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SimpleMobileTools/Simple-Gallery#95] opened 2016-12-12 18:19 UTC
When I open a picture from a folder with .nomedia, it always crash, but after remove .nomedia file, the app works to me.

**Comment by KrasnayaPloshchad** [comment] 2016-12-12 18:23
This can be reproduce with another file manager. For example, I used [X-plore](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore), I can long press the picture, then touch “Open with” to choose Simple Gallarg to open the picture, if the folder has .nomedia, then the app is forced quit.

**Comment by tp0** [comment] 2016-12-13 03:27
Same occurs here. Any file opened externally from a folder (or in parent folder) containing `.nomedia` causes immediate crash.

Reproduced with 1.51 from PlayStore

Same does not happen when Simple Gallery's own folder hide/unhide feature is used (not a workaround because I want to use .nomedia files).

**Comment by tibbi** [comment] 2017-01-06 16:06
Is it still happening? I cannot reproduce it. Havent tried reproducing with some older version.

**Comment by tp0** [comment] 2017-01-06 21:16
Yes, still happens, when photo is opened via file manager. On 2.2.0, which came out today (Play):

> Display images in .nomedia folders when "Show hidden folders" is checked

Was this meant to specifically address this issue? I'm not sure I understand what that setting is supposed to mean here.

**Comment by tibbi** [comment] 2017-01-06 21:32
It was not specifically about this issue. However you can enable the "Show hidden folders" switch in Settings and retest.

**Comment by tp0** [comment] 2017-01-07 06:34
I did, no difference.

I still don't understand what the setting is supposed to do. When enabled, ignore the existence of .nomedia file and show the folders in the gallery?

**Comment by tibbi** [comment] 2017-01-07 09:24
ye that setting is for toggling the visibility of both .nomedia folders and folders hidden in the app by the Hide function. Both cases work fine on my devices :/

**Comment by tibbi** [comment] 2017-01-07 18:56
please recheck with 2.2.1 which Im publishing now, Ive changed a couple things

**Comment by tp0** [comment] 2017-01-07 22:59
I can confirm the original bug (crashing when opening files in .nomedia folders) is now fixed.

**Comment by tp0** [comment] 2017-01-07 23:08
However, folders with .nomedia still won't up show up in the gallery even when "Show hidden folders" is enabled. Was this the intended behaviour? I don't know I'd want them to though, since when you hide a folder via SimpleGallery it doesn't create .nomedia file, so it makes sense if this hide/unhide and .nomedia are separate things? Another gallery app ([LeafPic](https://github.com/HoraApps/LeafPic)) mixes these up and in that I find it confusing.

**Comment by tibbi** [comment] 2017-01-07 23:12
it used to be messed up, but since 2.2.0 "Show hidden folders" treats both .nomedia and Hide folder the same way. So either both are hidden, or both are visible.

**Comment by Jalbre2** [comment] 2017-01-08 00:26
My folders with .nomedia files in them still don't show up on 2.2.1 with the setting enabled. I have cleared app data, reinstalled, forced refresh, etc. No luck yet.

How does it detect .nomedia files? Is it case sensitive? How are you placing the .Nomedia files on your device. Most of mine are placed by Quickpic, but I did use my computer for some.

**Comment by tibbi** [comment] 2017-01-08 09:04
its not case sensitive, just an empty ".nomedia" file created in any way. Ive tried adding and removing the file with my file manager, it worked properly.

**Comment by tp0** [comment] 2017-01-08 09:46
After testing a bit more [Solid Explorer](https://play.google.com/store/apps/details?id=pl.solidexplorer2) seems to be the problem. If I create the files in [Amaze](https://play.google.com/store/apps/details?id=com.amaze.filemanager), then it works as intended.

**Comment by touzainanboku** [comment] 2017-01-08 16:10
For me it doesn't display a single hidden folder. Most of my .nomedia files were added with MiXplorer, Solid Explorer, or QuickPic. Other apps like QuickPic, Cluttr, Vision and LeafPic show (at least some of) them just fine.

**Comment by KrasnayaPloshchad** [comment] 2017-01-08 20:29
After updating to version 2.2.1, this app works fine with me when I open an image from X-plore.

**Comment by tp0** [comment] 2017-01-11 09:40
After the update to 2.2.3 which included this:

> Revert to the previous way of obtaining images and videos

I had to recreate the .nomedia files, but after that everytying shows again correctly. Normal? (I have no idea how the Android OS indexing works.)

**Comment by tibbi** [comment] 2017-01-11 10:15
I will actually revert that revert, so we will be using a new way of getting the images, with some tweaks.

**Comment by KrasnayaPloshchad** [comment] 2017-01-11 13:21
I feel disappointed for version 2.2.3, this version crashes again for such folders.

**Comment by tp0** [comment] 2017-01-11 13:44
I forgot to test that... indeed it does again, but only when I create I the .nomedia files in Solid Explorer. Files created in Amaze File Manager = ok as in hidden properly and no crashing. Doesn't matter which file manger I use to open the files, only the one used to create .nomedia file matters.

**Comment by Jalbre2** [comment] 2017-01-11 17:10
At this point, I have not once seen one of my hidden folders show up in Simple Gallery. I have tried on 2.1.9, 2.2.0, 2.2.1, 2.2.2, and 2.2.3.

I just tried deleting and remaking a .nomedia file with amaze, and it had no effect. Actually, I just realized that the SG isn't even finding the folder when I remove the .nomedia file from it and no parent folders have one either. I wiped SG's data, and pulled down to refresh. It's just not showing up.

FWIW, QuickPic immediately notices the next time I open it.

I'm running Android 6.0.1 on a Nexus 6P

**Comment by tp0** [comment] 2017-01-12 07:16
I also noticed some other weird behaviour with 2.2.3 which only happened with .nomedia folders (*), but I will wait for the revert and new version to test more.

\* at least this one: if you move a photo to another folder and then back, opening it will cause a crash, even if you use SimpleGallery's own move feature for this)

**Comment by tibbi** [comment] 2017-01-12 08:45
obtaining images is such a mess, quickpic displays images which I dont see in the particular folder even if I plug the phone in my laptop... Im changing the way of getting the images more drastically, might take a couple days to implement. 

If you want some older .apk, you can easily download it from github releases too at https://github.com/SimpleMobileTools/Simple-Gallery/releases , I always attach an app-release.apk to new releases

**Comment by Jalbre2** [comment] 2017-01-12 15:37
FWIW, MTP when plugging into a computer is often unreliable regarding what files exist. I have had lots of issues with that in the past. Like creating a folder only to have the computer end up seeing it as a blank file. It may have something to do with the Android Media Scanner, since wiping the data from that tends to cause MTP to start behaving. 

Personally, I have never had QuickPic show a picture that I didn't see in another file explorer like Solid Explorer.

**Comment by touzainanboku** [comment] 2017-01-12 16:14
Yep, in my experience if the media store is broken, files won't show up correctly in MTP. I'd argue a file manager is a much more reliable way of checking if the file actually exists.

**Comment by tibbi** [comment] 2017-01-12 17:23
thats what I want to do now. Get a list of folders which contain some images, but get the individual images with the file manager way of doing things.

**Comment by touzainanboku** [comment] 2017-01-13 08:55
> but get the individual images with the file manager way of doing things.

I just compiled the master branch (after commit ae5113b1f0b5fb583cd0753231e0b1cd44fd4505) and it's now showing images that weren't showing up before because my media store was corrupt (they were showing up in QuickPic just fine). So that's great! Thanks for this.

**Comment by tibbi** [comment] 2017-01-13 23:02
ive published the new version into 2.3.0, check if images are displayed properly. I wasnt doing anything specific related to the .nomedia crash so if its fixed, its just luck.

**Comment by KrasnayaPloshchad** [comment] 2017-01-14 03:04
This version seems fine to me.

**Comment by tp0** [comment] 2017-01-18 20:50
\>2.3.0 versions seem fine. No more crashing.

ps. Solid Explorer definitely does something differently when creating .nomedia files than all other file managers I've tested. Hence, Solid Explorer shouldn't be used for testing the .nomedia visiblity in SimpleGallery. I've observed the same behaviour in LeafPic, QuickPic (classic version) and Motorola Gallery, so the issue must be in Solid Explorer.

**Comment by tibbi** [comment] 2017-01-18 20:51
ok thanks, Ill close it then

**Closed by tibbi** 2017-01-18 20:51 UTC
Labels: bug
