### ISSUE TITLE
[Feature Request] Directory Browsing / Explorer Mode

### ISSUE THREAD

**Issue by olifre** [SimpleMobileTools/Simple-Gallery#924] opened 2018-08-21 17:02 UTC
Right now, the app always appears to descend into all folders and creates a list. 
However, it's impossible to only show the folders of one level and "navigate" into the folders. 

For example, imagine a deep directory structure like this:
```
Work
|_ Project 1
|_ Project 2
Holidays
|_ New Zealand
   |_ 2017
   |_ 2018
|_ Italy
   |_ 2016
```
As long as the total number of recursively accessible directories is still small, it works fine, since Simple Gallery will display:
```
Work/Project 1
Work/Project 2
Holidays/New Zealand/2017
Holidays/New Zealand/2018
Holidays/Italy/2016
```
But once this increases, it would be more helpful to optionally be able to browse through directories, i.e. only show:
```
Work
Holidays
```
in the beginning, and then allow the user to descend into these. 

Hope my description is clear enough ;-).

**Comment by tibbi** [comment] 2018-08-22 06:41
ye I know what you mean. It is on the roadmap, duplicate of #292

**Closed by tibbi** 2018-08-22 06:41 UTC
