### ISSUE TITLE
Can't change colours and crop in one go

### ISSUE THREAD

**Issue by JohnVeness** [SimpleMobileTools/Simple-Gallery#1598] opened 2019-09-26 20:03 UTC
I want to edit an image to change its colours using the leftmost tool, *and* crop it, using the middle tool. As far as I can see, it isn't possible to do this without saving an intermediate version of the image. Can this be changed so it can be done in one?

**Comment by JohnVeness** [comment] 2019-09-26 20:09
Actually, it's worse than that. I can't seem to get the filter thing to take any effect. It changes on screen (preview?) as I try different filters, e.g. Clarendon, and I press the tick to save with a new filename, but the new file looks the same as the old one.

**Comment by tibbi** [comment] 2019-09-26 20:10
ye that is currently the intended behaviour, as sadly all primary actions are taken care of by different libraries. Merging it is on the roadmap, but it isnt that easy.

**Comment by JohnVeness** [comment] 2019-09-26 20:16
Actually, my first comment might actually be because I'm seeing issue #1500 and it isn't actually saving after all

**Comment by tibbi** [comment] 2019-09-26 20:17
there is no saving between primary actions (bottom line buttons), it just resets the image

**Comment by leaumar** [comment] 2019-10-06 19:48
I think this can be closed in favor of #685, which is a clear and simple case to enable this and other uses

**Comment by tibbi** [comment] 2019-10-06 20:03
not really, it isnt even a related issue

**Comment by leaumar** [comment] 2019-10-06 20:05
Granted, not entirely the same, but I think it would achieve the same functional result. I came here looking for background on making multiple edits to a single image, and found both these issues. Implementing #685 basically gives you a quick `Save` button after each edit, so that you can do multiple edits relatively consecutively.

**Comment by tibbi** [comment] 2019-10-06 20:24
Thats not the way I want to go, I want to avoid such hacks. Different parts of the editor definitely need to be merged, but it will be quite time consuming.

**Comment by user8446** [comment] 2019-10-16 02:07
I was looking to draw & crop on the same image and thought it was a bug and found this ticket.
I noticed that the draw editor caches the edit because if you switch to crop and back the drawing is still present. However, on the crop it edit is lost. 
Maybe if the edits were cached throughout it would eliminate #685 ?

**Comment by tibbi** [comment] 2019-10-16 07:45
it was already mentioned in the previous post, but that issue is about a whole different thing

**Comment by tibbi** [comment] 2019-12-30 21:20
the editor has been fully rewritten in version 6.11.0, this is already added there

**Closed by tibbi** 2019-12-30 21:20 UTC
Labels: feature request
