### ISSUE TITLE
Date/Time Modified is not kept at file moving/copying

### ISSUE THREAD

**Issue by gcalzo** [SimpleMobileTools/Simple-Gallery#1109] opened 2018-12-02 21:02 UTC
So, yesterday I got Android 8.1 in my Motorola G5 plus and I was really happy to check the "keep last modified timestamp" issue that, as declared by Google should be finally solved.

Well, I have tried copying file via MTP using the WIndows 10 Explorer interface on both internal memory and SDcard: **success!!!! Last Modify Timestamp kept!!!**

I have tried with a couple of Apps (ie Solid Explorer and another gallery tool) and again **moving files between internal and SDcard kept Last Modify Timestamp!**

**Finally I have tried Simple Galler Pro v6.0.2 and... IS NOT KEEPING THE TIMESTAMP!!!! :-( :-(**

**Comment by jmichael2497** [comment] 2019-01-15 22:54
Lineage OS 8.1.0 Oreo 2019-01-12 on an S5

f-droid Simple Gallery 6.2.0 sort by "last modified", "descending", "keep old last-modified value at file copy/move/rename", and "recycle bin".

f-droid Open Camera 1.44.1 using "Storage Access Framework" to save in standard external SD DCIM Camera folder.

any file movement or recycling does not preserve the "last modified" file system level timestamp, which is what i would expect to be preserved (embedded EXIF "last modified" obviously unchanged).

helpful hints for people troubleshooting:
- "last modified" is separate in file level vs embedded EXIF level.
- sorting by "last modified" uses file level vs "date taken" uses embedded EXIF level.
- the info screen shows the "last modified" embedded in EXIF rather than from the separate file level.

hope that helps.

**Comment by vanphong1310** [comment] 2019-03-27 12:33
It will be fixed soon?

**Comment by tibbi** [comment] 2019-03-27 16:12
it works fine on all of my devices, and as long as I cannot reproduce it, it is hard to fix. Ill take a look at it soon.

**Comment by vanphong1310** [comment] 2019-03-29 02:15
Thank you for your feedback.
On my device, when I use move to option to move image from internal storage to another folder in internal storage, the last modify timestamp of file is kept - nice :)
This bug appears when I move image from internal storage to SDcard or SDcard to another folder in same SDcard. I think this is a bug in write function when it work with SDcard storage.
My device: Samsung A9 Pro, Android 8.0.0, MicroSDXC Samsung EVO Plus U3 64GB with exFAT filesystem.

**Comment by vanphong1310** [comment] 2019-08-15 03:16
@tibbi Do you have any new information about this bug?

**Comment by vanphong1310** [comment] 2019-08-15 05:58
Hi @tibbi,
I clone this project and debug on my phone, i found this line [copyOldLastModified(source.path, destination.path)](https://github.com/SimpleMobileTools/Simple-Commons/blob/b1b6cfe15da895efcbdba5e6ea0170515eccc283/commons/src/main/kotlin/com/simplemobiletools/commons/asynctasks/CopyMoveTask.kt#L237), which cause the problem.
After this function call, the value of File(destination.path).lastModified() is reset to current time. But I can do `File(destination.path).setLastModified(File(source.path).lastModified())` to keep last modified time from source file.
Hope this information will be helpful to fix this bug soon :)

**Comment by tibbi** [comment] 2019-08-15 07:20
hm, interesting. How about date taken? Doesnt it get broken if you remove the copyOldLastModified() call? At sorting by date taken Im relying on mediastore data, so test it with sorting please. The ideal solution might be updating only DATE_TAKEN in that function and for last_modified I would just do that setLastModified() as you suggested.

**Comment by vanphong1310** [comment] 2019-08-15 10:30
I delete copyOldLastModified() call then move file from sd card to internal storage, last modified reset to current time and date taken is kept.
Seem like this function have no effect.

**Comment by tibbi** [comment] 2019-08-15 11:01
there are no issues at moving to the internal storage. If there are some issues, they happen at copying on an SD card. So the SD card has to be the destination. You can test proper Date Taken at sorting by it, checking an individual file properties usually has the proper data filled.

**Comment by vanphong1310** [comment] 2019-08-15 13:26
Only moving file from internal storage to internal storage is kept last modified time of file, in all other cases (sd card to sd scard, internal to sd card, sd card to internal) last modified time will be reset to current time. The reason for this promlem is [this code](https://github.com/SimpleMobileTools/Simple-Commons/blob/a0405dc63ccbd862d01767bf4734db27491fd30f/commons/src/main/kotlin/com/simplemobiletools/commons/activities/BaseSimpleActivity.kt#L284), it check if source or destination is on OTG or SD card then it move file by call startCopyMove() function ([it use bytes copy algorithm](https://github.com/SimpleMobileTools/Simple-Commons/blob/a0405dc63ccbd862d01767bf4734db27491fd30f/commons/src/main/kotlin/com/simplemobiletools/commons/asynctasks/CopyMoveTask.kt#L225)) so it need manually copy last_modified attribute, if source and destination is on internal storage then it use renameTo() function.
I tried remove copyOldLastModified() call and do all cases of moving, the date taken is kept as source file. I checked it by properties option in three dot  menu and sort by feature.

**Comment by tibbi** [comment] 2019-08-15 18:48
can you try the latest version of the app, with commons 5.16.10? I added your copy/move suggestion there, to see if it fixes anything in some cases. Thanks

**Comment by vanphong1310** [comment] 2019-08-17 03:43
Hello @tibbi, I have been testing it, this bug is gone, not any other problems, so you can close this issue.
How long this patch is available in store?

**Comment by tibbi** [comment] 2019-08-17 07:10
Ill release a new version within a couple days, when a few more things will be fixed. Anyway, Ill close it, reopen it if it will still be broken at 6.10.0. Thanks

**Closed by tibbi** 2019-08-17 07:10 UTC
Labels: bug
