### ISSUE TITLE
When add including Android/data folder showing error

### ISSUE THREAD

**Issue by AdityaMishra135** [SimpleMobileTools/Simple-Gallery#2988] opened 2023-09-25 16:55 UTC
Can't access data folder and . nomedia files from Android/data

**Comment by Aga-C** [comment] 2023-09-25 17:14
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2988.

**Comment by Aga-C** [comment] 2023-09-25 17:15
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2869.

**Closed** 2023-09-26 08:20 UTC
