### ISSUE TITLE
TIFF images not shown

### ISSUE THREAD

**Issue by hman2** [SimpleMobileTools/Simple-Gallery#1622] opened 2019-10-27 22:24 UTC
Files of the popular TIFF format are not shown. Not their image content, but even the entire file does not show up in a folder, so I cannot be selected in Simple Gallery... When called from outside to show a TIFF image (i.e. by calling Simple Gallery from Amaze), another image from the same folder is shown instead.

**Comment by tibbi** [comment] 2019-10-28 07:45
duplicate of #663

**Closed by tibbi** 2019-10-28 07:45 UTC
