### ISSUE TITLE
Sort by creation date is not valid

### ISSUE THREAD

**Issue by vantu5z** [SimpleMobileTools/Simple-Gallery#2516] opened 2022-06-14 07:05 UTC
Does not sort by creation date.
If I edit some photo I want to see it near original. Choose for that `Sort by -> Creation time` but it sorted by edit date.

**Comment by tibbi** [comment] 2022-06-14 09:33
Hello, try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

**Comment by vantu5z** [comment] 2022-06-14 10:15
Hmm, `Menu -> Fix Date` works.
I edit and `save as` photo by another app, in file info in this app I see both valid `edit date` and `create date`, but sort does not work.
After fix no visible changes in info, but sort is working now. And witch date is it fix?
I can suppose only that property name is differ...
Any way, if we can fix the create date, why we can't sort by this invalid date (fix it on fly in the app with no file modification)?

**Comment by tibbi** [comment] 2022-06-14 10:17
so Ill close this as the issue is with the foss editor changing Date Taken, not sorting itself

**Comment by vantu5z** [comment] 2022-06-14 10:25
App show me valid `Date Taken`, but can't sort by it. I think that is app sorting issue.

**Comment by tibbi** [comment] 2022-06-14 10:27
you said that Menu -> Fix Date works, so just fix it with that. Will keep an eye on it too.

**Closed by tibbi** 2022-06-14 10:27 UTC
