### ISSUE TITLE
Group by date

### ISSUE THREAD

**Issue by Wiredframe** [SimpleMobileTools/Simple-Gallery#467] opened 2017-11-20 20:17 UTC
It would be nice if Simple Gallery would have a view option for each album that groups the items by date. This view is called "moments" in other galleries and helps to group photos that were made on a trip or so.

**Comment by fpetry** [comment] 2018-04-19 10:00
+

**Comment by tibbi** [comment] 2018-04-27 19:27
duplicate of #709

**Closed by tibbi** 2018-04-27 19:27 UTC
Labels: feature request
