### ISSUE TITLE
Viewing a large WebP image crashes the app

### ISSUE THREAD

**Issue by liquidtown** [SimpleMobileTools/Simple-Gallery#2784] opened 2023-02-25 22:18 UTC
Just to clarify most of the WebP images I tried are viewable. I'm not sure if this bug applies to other image/video formats.

https://user-images.githubusercontent.com/73709976/221382034-a2d62932-2aa7-4849-a4b3-89fee515f53d.mp4

**Comment by tibbi** [comment] 2023-02-26 17:35
can you reproduce it with specific images, or it is random? If it is random, guess you will be running out of memory and the app isnt handling it fully.

**Comment by liquidtown** [comment] 2023-02-26 20:20
> can you reproduce it with specific images, or it is random? If it is random, guess you will be running out of memory and the app isnt handling it fully.

Yes, the same images crash the app. I've also had the same issue with the same images on a Moto G Power 2022 and a Samsung Galaxy J3V.

**Comment by tibbi** [comment] 2023-02-26 20:30
can you attach the file?

**Comment by liquidtown** [comment] 2023-02-26 22:15
[Images.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/10834869/Images.zip)
Opening "_mu_Core.webp" or "Metal 2.1.webp" will instantly crash the app. "Drone 1.webp" is an example image that works fine.

**Comment by tibbi** [comment] 2023-04-16 19:09
I guess it is a duplicate of #2828

**Closed by tibbi** 2023-04-16 19:09 UTC

**Comment by saefthe** [comment] 2023-04-16 20:22
شكرا لكم

Saef

في الأحد، ١٦ نيسان ٢٠٢٣, ١٠:٠٩ م Tibor Kaputa ***@***.***>
كتب:
