### ISSUE TITLE
EXIF Altering

### ISSUE THREAD

**Issue by nulledone** [SimpleMobileTools/Simple-Gallery#686] opened 2018-03-04 00:46 UTC
Options to remove all EXIF and click alter them in file properties dialog.

Would be a lot better to show all EXIF properties in additional second page of the dialog

Sample

(header) (removeallicon) 
Taken time (remove icon) (editicon)
01.01.1970

**Comment by ramack** [comment] 2018-04-15 20:27
Not only removeing, but also modification and additon of EXIF tags would be great!

**Comment by krc** [comment] 2018-12-12 19:48
Would be nice to see all exif data
even nicer to edit/remove. but I'd settle for visibility

**Comment by tibbi** [comment] 2019-12-09 21:36
duplicate of #282

**Closed by tibbi** 2019-12-09 21:36 UTC
Labels: feature request
