### ISSUE TITLE
Feature request: Play AV1 Videos

### ISSUE THREAD

**Issue by hubertmeier** [SimpleMobileTools/Simple-Gallery#2680] opened 2022-12-03 10:05 UTC
AV1 coded videos show no picture, only audio ...

Thank you

**Comment by Aga-C** [comment] 2022-12-03 10:22
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2496.

**Comment by tibbi** [comment] 2022-12-03 10:23
duplicate of #2496

**Closed by tibbi** 2022-12-03 10:23 UTC
