### ISSUE TITLE
One finger zoom issue

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1343] opened 2019-03-19 02:07 UTC
If you perform a one finger zoom and swipe to either left or right, instead of just moving around the image, the next/previous media will be shown.

**Comment by tibbi** [comment] 2019-03-19 07:59
works fine to me. What app version do you have?

**Comment by floppyD** [comment] 2019-03-19 11:29
6.6.0
https://youtu.be/93UF6JHFft4

**Comment by tibbi** [comment] 2019-03-19 12:10
aha Im aware of that. It isnt related to one finger zooming, just zooming in in general. Duplicate of #1256

**Closed by tibbi** 2019-03-19 12:10 UTC
