### ISSUE TITLE
Play consecutive videos seamlessly

### ISSUE THREAD

**Issue by pmattke** [SimpleMobileTools/Simple-Gallery#916] opened 2018-08-14 22:37 UTC
## As hobby videographer, I am taking lots of short clips using my smartphone camera. I want a possibility to play them all in a seamless way, without swiping transitions. Just like the single scenes would play on a good old cassette camcorder. Many short scenes visually "stitched" together.

Why did no one bring that good old camcorder experience to modern smartphones yet?

As far as I see, Simple Gallery uses ExoPlayer, and afaik ExoPlayer can seamlessly play multiple videos after each other. Normally, when taking multiple video clips, they somehow belong to each other and it would be nice if they could be played seamlessly without swipe transition or sth else.

Here some proposals:
* PROPOSAL 1: implement config option like "play next video after video ended"
  * turning this one on would at first obviously disable the option "loop video" - both can't be active at the same time
  * if you have it on, then after one video is played, the next one should be played immediately in the same player, without swipe transition. of course you could still skip clips by swiping through your assets just normally
  * the same thing would be true for slideshow. just play consecutive video files in one exoPlayer. without swipe animation
  * if "play next video after video ended" the slideshow would look just like now. swipe transition effect even between consecutive videos
* PROPOSAL 2: no new config option, but seamless video playback for slideshows always
  * this one would not increase config complexity because no additional config switch is needed
  * normal swiping through media would work just the same as now
  * playing consecutive videos in a slide show would end up in using one single exo player instance which plays them all seamlessly. all videos play seamlessly without swipe transition effect until they are interrupted  by a photo or some other media type

**Comment by tibbi** [comment] 2018-08-15 06:30
so all you basically ask is no-animation in slideshows, duplicate of #359

**Closed by tibbi** 2018-08-15 06:30 UTC

**Comment by pmattke** [comment] 2018-08-15 07:15
Well, not completely. Because I personally prefer "proposal 1". It's a special config switch (turned off by default), which would also change the behaviour of normal "swipe through media" without slideshow, when turned on. The idea is not changing the transition effect, but automatically playing the next video, if there is one, when the first one ended. If the next media asset is a photo or so, it won't show it. In this case, the video sequence playback would just end.

So this idea would, when turned on, have effect on both slideshow and no-slideshow. 

Also technically, it's not just "no animation". It would use the same `VideoFragment` and `ExoPlayer` instance together with something like [`ConcatenatingVideoSource`](https://medium.com/google-exoplayer/dynamic-playlists-with-exoplayer-6f53e54a56c0)

**Comment by tibbi** [comment] 2018-08-15 08:11
you can already filter out images from the slideshow

**Comment by pmattke** [comment] 2018-08-15 09:08
thought about it one more time. there was some misunderstanding somewhere, I was not talking about leaving images out from the slideshow, but I think I also confused myself a bit :grin:

after all, I think it would be all fine with an option to make a slideshow without transition effects
