### ISSUE TITLE
[Request] Password Protect Specific Folders

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [SimpleMobileTools/Simple-Gallery#1435] opened 2019-05-24 14:40 UTC
Would really love to have an option to password protect and hide/encrypt specific folders (Different from the "hidden folders").

To view them you would do something along the lines of: Locked files (Folders hidden from normal viewing > unlock (fingerprint/pin/swipe/pass) > shows locked files > backout (relocks files and hides them from view)

**Comment by tibbi** [comment] 2019-05-24 18:03
duplicate of #379

**Closed by tibbi** 2019-05-24 18:03 UTC
