### ISSUE TITLE
Weird consequences to the change in folder view

### ISSUE THREAD

**Issue by lbdroid** [SimpleMobileTools/Simple-Gallery#1414] opened 2019-05-09 14:19 UTC
Edit: actually seems to be this commit; https://github.com/SimpleMobileTools/Simple-Gallery/commit/afa29ec5b16ef0ecd11f457b9817ab0ccca2182d

What I'm seeing now, is that any directory that is a direct subdirectory of the root of the "external" path, will be shown as a subdirectory of "0".

Note that within the Android storage system, the external storage path corresponds to the physical path /data/media/0/

**Comment by tibbi** [comment] 2019-05-09 18:24
duplicate of #1413

**Comment by lbdroid** [comment] 2019-05-09 20:13
Not actually a duplicate. It pertains to the same commit, however, I'm actually referring to it mangling the paths at the root of the external storage.

**Comment by tibbi** [comment] 2019-05-09 20:24
but if the folder is a standalone one, you see it as "Internal"?

**Comment by lbdroid** [comment] 2019-05-09 20:27
What I see, is if I have, lets say 3 directories in the root of the external storage (fake sdcard), named "a", "b", and "c", each with pictures in them, then in simple gallery, it shows "0 (3)", and if I open it, it shows three directories "a", "b", and "c".

It would be my expectation that any directory off the storage root would be displayed separately at simple gallery's root.

**Comment by tibbi** [comment] 2019-05-09 21:06
right, I see what you mean. It is a different issue then indeed.

**Closed** 2019-05-13 08:30 UTC
