### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by OLEG4120** [SimpleMobileTools/Simple-Gallery#781] opened 2018-05-25 06:45 UTC
App crash when del some files and try open other one.

```
Process: com.simplemobiletools.gallery
Flags: 0x38c8be44
Package: com.simplemobiletools.gallery v177 (4.0.0)
Foreground: Yes
Build: motorola/montana_retru_n/montana_n:7.1.1/NPP26.102-27/31:user/release-keys

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	... 1 more
Caused by: java.io.FileNotFoundException: /storage/DE7E-14FE/Media/IMG_20180523_204713493_BURST000_COVER_TOP.jpg (Permission denied)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:99)
	at android.media.ExifInterface.<init>(ExifInterface.java:1106)
	at com.simplemobiletools.gallery.fragments.ViewPagerFragment.getMediumExtendedDetails(SourceFile:33)
	at com.simplemobiletools.gallery.fragments.PhotoFragment.checkExtendedDetails(SourceFile:382)
	at com.simplemobiletools.gallery.fragments.PhotoFragment.onCreateView(SourceFile:119)
	at android.support.v4.app.Fragment.performCreateView(SourceFile:2346)
	at android.support.v4.app.n.a(SourceFile:1428)
	at android.support.v4.app.n.f(SourceFile:1759)
	at android.support.v4.app.n.a(SourceFile:1827)
	at android.support.v4.app.d.f(SourceFile:797)
	at android.support.v4.app.n.b(SourceFile:2596)
	at android.support.v4.app.n.a(SourceFile:2383)
	at android.support.v4.app.n.b(SourceFile:2338)
	at android.support.v4.app.n.b(SourceFile:2215)
	at android.support.v4.app.d.e(SourceFile:649)
	at android.support.v4.app.r.finishUpdate(SourceFile:167)
	at android.support.v4.g.v.populate(SourceFile:1238)
	at android.support.v4.g.v.populate(SourceFile:1086)
	at android.support.v4.g.v.setAdapter(SourceFile:534)
	at com.b.a.b.setAdapter(SourceFile:129)
	at com.simplemobiletools.gallery.activities.ViewPagerActivity.updatePagerItems(SourceFile:316)
	at com.simplemobiletools.gallery.activities.ViewPagerActivity.gotMedia(SourceFile:815)
	at com.simplemobiletools.gallery.activities.ViewPagerActivity.access$gotMedia(SourceFile:54)
	at com.simplemobiletools.gallery.activities.ViewPagerActivity$initViewPager$2.invoke(SourceFile:212)
	at com.simplemobiletools.gallery.activities.ViewPagerActivity$initViewPager$2.invoke(SourceFile:54)
	at com.simplemobiletools.commons.extensions.ViewKt$onGlobalLayout$1.onGlobalLayout(SourceFile:29)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2124)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1272)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	... 3 more
```

**Comment by tibbi** [comment] 2018-05-25 10:43
cannot reproduce. Does it happen after every delete? If you have Extended Details enabled, can you try disabling it?

**Comment by OLEG4120** [comment] 2018-05-25 10:52
It doesn't every delete.
File deletes in background thread, right? It seems that crash happens when "delete thread" doesn't complete job, but I try open other file

**Comment by tibbi** [comment] 2018-05-25 13:54
ye the delete happens on a background thread, but Im removing the item from the thumbnails view instantly with an animation. I havent seen such crashes in the logs so it definitely isnt a critical issue, Ill try reproducing it again someday.

**Comment by tibbi** [comment] 2019-02-26 21:53
should be fixed already

**Closed by tibbi** 2019-02-26 21:53 UTC
Labels: bug
