### ISSUE TITLE
Allow Hidden Directory

### ISSUE THREAD

**Issue by And96** [SimpleMobileTools/Simple-Gallery#2429] opened 2022-04-24 17:04 UTC
Since it's a Google Play Store limitation only.
It's not necessary to disable that feature on APK version and on F-Droid version.

It's one of the best and most requested feature, and in my and a lot of others cases the only way we use this app.

Many users ask for this.
https://www.reddit.com/r/SimpleMobileTools/comments/u8mmcd/why_cant_see_hidden_directory_anymore/

**Comment by tibbi** [comment] 2022-04-24 17:27
duplicate of #2419

**Closed by tibbi** 2022-04-24 17:27 UTC

**Comment by And96** [comment] 2022-04-24 17:58
Why closed ?

**Comment by tibbi** [comment] 2022-04-24 19:15
because we cannot add it back. Adding some hacks into the f-droid version would just delay the inevitable

**Comment by And96** [comment] 2022-05-17 13:31
I can see FOSS version actually added back the feature.

Great!!

**Comment by woheller69** [comment] 2022-05-22 16:16
> I can see FOSS version actually added back the feature.
> 
> Great!!

It added the possibility to hide folders but not to show hidden folders...

**Comment by And96** [comment] 2022-05-29 13:56
> > I can see FOSS version actually added back the feature.
> > 
> > Great!!
> 
> It added the possibility to hide folders but not to show hidden folders...

That's not true. I can show hidden directory

**Comment by JagerSprinkles** [comment] 2022-06-03 14:05
> > > I can see FOSS version actually added back the feature.
> > > Great!!
> > 
> > 
> > It added the possibility to hide folders but not to show hidden folders...
> 
> That's not true. I can show hidden directory

The "Temporarily show hidden" menu option is still missing from the latest FOSS version. Had to downgrade to 6.22.3 to get it back.

**Comment by tibbi** [comment] 2022-06-03 14:42
its there, just give the app All files access.
