### ISSUE TITLE
[Bug] Deleted pictures are showing too slow

### ISSUE THREAD

**Issue by lipici** [SimpleMobileTools/Simple-Gallery#2242] opened 2021-10-14 10:40 UTC
[Bug] Deleted pictures are showing too slow in recicle bin and deleted files from recicle bin, same, too slow.
You have the impression you deleted another folder and you have to wait if you deleted the right folder.
Thank you.

**Comment by tibbi** [comment] 2021-10-14 12:47
what app and OS version are you using?

**Comment by tibbi** [comment] 2021-10-14 16:59
you mean that the folder thumbnail and info on the main screen is slow to refresh? Or if you open the recycle bin itself, files are slow to appear? Like what do you mean by slow anyway? How many seconds?

**Comment by lipici** [comment] 2021-10-14 19:03
Hello again. I mean  that the folder thumbnail and info on the main screen is slow to refresh. 
Deleting a folder from gallery is slow to refresh. Also deleting the recicle bin with 3 pictures in it is slow to refresh.
Like 5 seconds. 
I delete the folder and stays there for 5 seconds before it dissapears and creates that sensation that i deleted another folder if takes like 5-6 s!conds before it dissapears.

**Comment by tibbi** [comment] 2021-10-14 19:07
Ok, it is a generic performance issue then, duplicate of #2181

**Closed as completed by tibbi** 2021-10-14 19:07 UTC
