### ISSUE TITLE
Batch file rename text color doesn't use app-wide text color 

### ISSUE THREAD

**Issue by bchauSW** [SimpleMobileTools/Simple-Gallery#1551] opened 2019-08-14 08:44 UTC
I set the app text color to be black and the background to be white.

When I select multiple images to rename, the text color is white, and with the white background, the text is unreadable.

Should the text color match the rest of the app?

**Comment by tibbi** [comment] 2019-08-14 09:33
so the issue isnt related to renaming, just selecting items, right? What app version do you have? It seems to be related to some system update, check if there is none available.

**Comment by bchauSW** [comment] 2019-08-14 12:43
I guess so -- specifically, the disposal that appears that provides me information on what I'm renaming.

I have version 6.9.2 from F-Droid, and I do not have any additional system updates for my OS (Android 9, which is Pie I thjnk).

**Comment by tibbi** [comment] 2019-08-14 13:46
can you send me a screenshot of the issue? Im not sure what you mean now.

**Comment by bchauSW** [comment] 2019-08-15 02:26
![Here is a screenshot](https://user-images.githubusercontent.com/51136061/63068761-49f4e180-bec9-11e9-9891-70ebfb90183f.png)

I highlighted multiple images, selected the option menu in the upper right hand corner, and selected Rename.

**Comment by tibbi** [comment] 2019-08-15 07:21
can you also send a screenshot of your Customize Colors screen? Just to make it easier to reproduce the issue. Thanks

**Comment by bchauSW** [comment] 2019-08-15 12:08
![Here is a screenshot of the Customize Colors screen.(https://user-images.githubusercontent.com/51136061/63093555-99173280-bf1a-11e9-84bd-b7d88877c002.png).

**Comment by tibbi** [comment] 2019-08-15 12:24
alright, I could reproduce it like that. It will be fixed in the next version 6.9.3. Thanks

**Closed by tibbi** 2019-08-15 12:24 UTC
