### ISSUE TITLE
Strange beahaviour in Fullscreen Mode with 27 MP Pixel from Xiaomi Note 10 pro on this device

### ISSUE THREAD

**Issue by hubertmeier** [SimpleMobileTools/Simple-Gallery#1935] opened 2020-10-11 12:04 UTC
I have a very strange behaviour on this device only which pictures which are made on the device with 27 MP. There are a lot of screenshots to explain this. This issue occured after an update some versions ago (i do not know which, its since two or three month and i hoped it will disappear with an update ...

**Portrait mode**

If i take these pictures and open simple gallery the thumbnails are correct.

![Screenshot_2020-10-11-10-25-44-076_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/20687189/95677931-6245b680-0bc9-11eb-98d6-bda370785115.jpg)

if i click on the picture the picture opens and fit into the screen for some seconds

![Screenshot_2020-10-11-10-26-04-344_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/20687189/95677953-77bae080-0bc9-11eb-88e2-dd751a537448.jpg)

Some seconds later the picture looks like on the following screenshot

![Screenshot_2020-10-11-10-26-19-450_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/20687189/95677962-899c8380-0bc9-11eb-9fc2-7acb8c4c894e.jpg)

If i double click the whole picture is bigger but not correct

![Screenshot_2020-10-11-10-26-36-048_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/20687189/95677969-9c16bd00-0bc9-11eb-9343-ade16db684bd.jpg)

If i turn the phone the picture fits in the screen and looks ok, at double click too ...

**Landscape mode**

![Screenshot_2020-10-11-10-50-14-077_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/20687189/95677990-c5cfe400-0bc9-11eb-90b5-b12045807f62.jpg)

If i click on the picture, it fits on the screen, thats ok

![Screenshot_2020-10-11-10-50-32-150_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/20687189/95678022-ed26b100-0bc9-11eb-94d5-edc9c9d7201c.jpg)

If i double click the picture the picture seems to have the size of the full resolution but there are strange artifacts on the lines, it seems that a smaller version is resized.

![Screenshot_2020-10-11-10-51-05-033_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/20687189/95678061-2d862f00-0bca-11eb-8aa3-2cf4f8f2b2f4.jpg)

I have the same software on a samsung S9 and there are no problems, even the transferred originals from the Note 9 are displayed correctly.

If i have bigger files like 42 MPixel Pictures from a Sony A7RM2 they will displayed correctly on both devices. If its needed i will upload the orogonal pictures ... they are about 10-12 MBytes.

Thank you for your really nice software.

**Comment by tibbi** [comment] 2020-10-11 16:05
What app version and OS version? Where did you get the app from?

**Comment by hubertmeier** [comment] 2020-10-12 17:28
v6.16.1 from F-Droid, Android 10, MIUI 12

this is really very strange ... i think there are 3 or 4 updates since this happened (direct after an update). in older Galaxy Tab S Android 4 it works fine too, there is a Problem with zooming ... Double tapping sizes the picture much bigger than 100% nur that is not really important.

**Comment by hubertmeier** [comment] 2020-10-12 17:32
it seems similar to the issue #1895 ...

**Comment by tibbi** [comment] 2020-10-13 10:42
it is actually a duplicate of #1895

**Closed by tibbi** 2020-10-13 10:42 UTC
