### ISSUE TITLE
Hidden image feature

### ISSUE THREAD

**Issue by paolo-caroni** [SimpleMobileTools/Simple-Gallery#2463] opened 2022-05-13 10:21 UTC
On previous version was possible to hidden image, and press a button to show hidden images.... on the stable version the hidden feature  is removed. Why?

**Comment by tibbi** [comment] 2022-05-13 10:22
it cannot be there anymore due to some system restrictions, duplicate of #2419

**Closed by tibbi** 2022-05-13 10:22 UTC

**Comment by OkyDooky** [comment] 2022-05-13 20:48
@paolo-caroni For now, Tibbi explained that you can "hide" folders using the "Exclude" function that is built in. It is not as convenient as the "Hide" function, since you cannot easily show excluded folders and have to into Settings to manually remove them from the Excluded list.
So, until this workflow can be improved, a workaround would be to take the images you want to hide and move them into a unique folder and then Exclude it.
