### ISSUE TITLE
Large png images get distorted in editor

### ISSUE THREAD

**Issue by jamtse** [SimpleMobileTools/Simple-Gallery#1748] opened 2020-02-15 10:15 UTC
After editing an png image (attempted croping and painting separately), curves that looked smooth in the original image looks jagged in the edited version. I saw this in a 1700x2000 size image, but attempting to reproduce in a 400x400 image showed no noticable degradation in quality.

Tested on v 6.12.5 Pro
Attaching example with just some paint applied in the editor.
![sketch-1581759691976](https://user-images.githubusercontent.com/4234404/74586076-1e6fc280-4fe4-11ea-94e0-48270104d77d.png)
![sketch-1581759691976_2](https://user-images.githubusercontent.com/4234404/74586079-26c7fd80-4fe4-11ea-8747-1864b28018d5.png)

**Comment by tibbi** [comment] 2020-02-15 12:21
ye the image quality at cropping can be glitchy, duplicate of #1744

**Closed by tibbi** 2020-02-15 12:21 UTC

**Comment by jamtse** [comment] 2020-02-15 14:33
Right, figured it might be separate issues as this happened even on other edits, with no croping involved, and the other ticket mentioned it being more visible with sizes < 1000 pixels. But I trust you have better grasp of the problem. =)
