### ISSUE TITLE
"Pull-to-refresh" triggered while long-press-dragging to select multiple

### ISSUE THREAD

**Issue by e-t-l** [SimpleMobileTools/Simple-Gallery#2682] opened 2022-12-04 21:21 UTC
It's awesome that Simple Gallery includes the intuitive "select multiple" function of long-pressing then dragging over multiple items. However, sometimes when this is done (especially if started from an item in the top row), if the "pull down to refresh" setting is enabled, then that refresh function is triggered. This isn't catastrophic in itself, but I think there may be some conflict between these two functions, because the ProgressCircle freezes.

I suggest that when a long press triggers the multi-select function, the pull-to-refresh function should be blocked from receiving the gesture.

**Comment by tibbi** [comment] 2022-12-05 09:21
duplicate of #1743

**Closed by tibbi** 2022-12-05 09:21 UTC
