### ISSUE TITLE
Support for HEIC files? 

### ISSUE THREAD

**Issue by edent** [SimpleMobileTools/Simple-Gallery#1333] opened 2019-03-13 09:12 UTC
Would it be possible to support viewing HEIC photos in the gallery?

If I open them in my phone's native gallery (OnePlus 5T) they are viewable. But they don't display in Simple Gallery, either as a thumbnail or a full image.

Thanks!

**Comment by tibbi** [comment] 2019-03-13 09:25
duplicate of #893

**Closed by tibbi** 2019-03-13 09:25 UTC
