### ISSUE TITLE
Feature request: Show AV1-video thumbnails

### ISSUE THREAD

**Issue by hubertmeier** [SimpleMobileTools/Simple-Gallery#2681] opened 2022-12-03 10:07 UTC
while AV1 videos are not supported by the player, i can use vlc for playing videos. A thumbnails of the video would be nice ...

Thank you

**Comment by Aga-C** [comment] 2022-12-03 10:22
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2496.

**Comment by tibbi** [comment] 2022-12-03 10:23
duplicate of #2496

**Closed by tibbi** 2022-12-03 10:23 UTC
