### ISSUE TITLE
Select on single image view

### ISSUE THREAD

**Issue by trespda** [SimpleMobileTools/Simple-Gallery#2940] opened 2023-08-07 17:07 UTC
In the Samsung native gallery, it is possible to long press a thumbnail in folder view to select, enter, and continue swiping and selecting single images on the go. It is an easy natural way to select with maximal fit, without the noise of other images, in one flow with manipulating the view. Can it be implemented here? Can for example a select action by long press added to single view, or a select button added to the horizontal more actions bar?

**Comment by Aga-C** [comment] 2023-08-07 17:41
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/315.

**Closed** 2023-08-14 16:06 UTC
