### ISSUE TITLE
Can not 1:1 zooming square images

### ISSUE THREAD

**Issue by pingplug** [SimpleMobileTools/Simple-Gallery#2912] opened 2023-07-25 23:46 UTC
Version: 6.27.0
System: Harmony OS 3.0.0
Problem:
With "1:1 zooming in with two double taps" on, after the second double tap, the square image will shrink back to the initial size. If the image is not square, everything is OK.

**Comment by Aga-C** [comment] 2023-07-26 05:40
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/1681.

**Closed** 2023-07-26 14:39 UTC
