### ISSUE TITLE
Change icon colors are unusable in adaptive launchers

### ISSUE THREAD

**Issue by Alexanderlll** [SimpleMobileTools/Simple-Gallery#1533] opened 2019-08-01 00:40 UTC
Trebuchet launcher, in Recents the icon is changed, but not working in app drawer, then i deactivate adaptive icons and works but breaks my other adaptive apps like LineageOS Clock, Messaging, Recorder and all apps wich uses adaptive from LineageOS, i suggest a previously assigned color for each SimpleMobileTools apps, each app with his own different color instead of the orange for all apps, this resolves the issues with launchers with adaptive capabilities because the SimpleMobileTools apps got different colors already and there is no need to change icon colors, but, still got the change icon color capabilities if necesary in other launchers with no adaptive icons support, or the posibility for adaptive icons in SimpleMobileTools apps, Thanks a lot for your time

![Screenshot_20190731-181856](https://user-images.githubusercontent.com/53236433/62256978-b697b880-b3c0-11e9-9129-f3cc6bf66c9f.png)
![Screenshot_20190731-181906](https://user-images.githubusercontent.com/53236433/62256979-b697b880-b3c0-11e9-8098-b2e7c7ecf0c1.png)
![Screenshot_20190731-181927](https://user-images.githubusercontent.com/53236433/62256980-b697b880-b3c0-11e9-969c-771c32daa137.png)

**Comment by tibbi** [comment] 2019-08-01 07:26
duplicate of https://github.com/SimpleMobileTools/General-Discussion/issues/94

**Closed by tibbi** 2019-08-01 07:26 UTC
