### ISSUE TITLE
new image resizing option. do not stretch small images

### ISSUE THREAD

**Issue by OmlineEditor** [SimpleMobileTools/Simple-Gallery#2221] opened 2021-09-12 19:22 UTC
now if the image is small, the program stretches this image to the size of the screen.
please add the ability to stretch the image to the screen size if it is larger than the screen size.
if the image is smaller than the screen size, please do not stretch its edges of the screen and show it at a scale of 100% on a part of the screen.

**Comment by tibbi** [comment] 2021-09-12 19:28
duplicate of #104

**Closed by tibbi** 2021-09-12 19:28 UTC
