### ISSUE TITLE
Grid View with aspect ratio option to reduce empty space between thumbnails

### ISSUE THREAD

**Issue by Talon01** [SimpleMobileTools/Simple-Gallery#1732] opened 2020-01-31 05:42 UTC
I deactivated "Crop thumbnails into squared" in settings.
Grid view always uses 1:1 aspect ratio box and places thumbnail images inside.
This way a lot of empty space is between rows of images (see attachment below).

Please add a setting which lets define the aspect ratio for thumbnails in grid view, e. g.
- 16:9
- 4:3
- 1:1
- 3:4
- 9:16

Another option would be to detect the row size of thumbnails dynamically.
Give all thumbnails the same width (e. g. 33% if column count is 3)
Use as row size the image with maximum height
Place images vertically centered.

Both options can reduce horizontal empty space for non square images.
I prefer second option, but I am also happy with first option which might quite easy to implement :-)

----
![Screenshot_20200131-053924](https://user-images.githubusercontent.com/8125672/73514744-1d8b3e00-43f3-11ea-945a-f98065c8dab0.png)

**Comment by tibbi** [comment] 2020-01-31 08:27
duplicate of #1567

**Closed by tibbi** 2020-01-31 08:27 UTC

**Comment by Talon01** [comment] 2020-01-31 08:49
It's not an exact duplicate.
It suggests alternate solutions to staggered view (which might be easier to implement).

Anyways, any solution is highly appreciated and will improve the grid view.
