### ISSUE TITLE
[Bug] Share videos

### ISSUE THREAD

**Issue by black-cerberon** [SimpleMobileTools/Simple-Gallery#1873] opened 2020-06-30 11:38 UTC
Android 9
Simple Gallery v.6.15.2 Pro

Bug description: App not show existing videos when I try choose them and share through another app. 

For reproduce: Any app > Send file (or share) > Recent > swipe right and tap Simple Gallery > no one video file not visible.

**Comment by tibbi** [comment] 2020-06-30 13:06
Well, dont you have videos filtered out at the top Menu -> Filter? If you launch Simple Gallery the casual way, do videos show up?

**Comment by black-cerberon** [comment] 2020-06-30 13:17
> Well, dont you have videos filtered out at the top Menu -> Filter?
All marks enabled.
If you launch Simple Gallery the casual way, do videos show up?
Yes.

**Comment by tibbi** [comment] 2020-06-30 13:31
I need more exact steps for reproduction. It definitely isnt "Any app", tell one where I could reproduce it properly.

**Comment by black-cerberon** [comment] 2020-06-30 13:49
This app https://github.com/Mishiranu/Dashchan

**Comment by tibbi** [comment] 2020-06-30 21:28
that is a heavily deprecated app, you shouldnt be using these. Does it happen in any other app?

**Comment by black-cerberon** [comment] 2020-07-01 07:32
Snapseed, but this app for images. Anyway, if I choose default gallery or Leafpic instead Simple Gallery, videos will be show up.

**Comment by cunninglemming** [comment] 2021-11-01 01:03
I think this is the duplicate of #1828

**Comment by tibbi** [comment] 2021-11-01 09:28
still needs steps for reproducing

**Closed by tibbi** 2021-11-01 09:28 UTC
Labels: bug

**Comment by cunninglemming** [comment] 2021-11-01 12:17
I thought this comment [here](https://github.com/SimpleMobileTools/Simple-Gallery/issues/1828#issuecomment-863275135) explained it well, no?

**Comment by tibbi** [comment] 2021-11-01 12:23
I didnt close that issue
