### ISSUE TITLE
Faster image loading speed

### ISSUE THREAD

**Issue by DeepSeaUnited** [SimpleMobileTools/Simple-Gallery#3006] opened 2023-10-13 08:43 UTC
Image does not appear fast enough when I scroll down fast. I hope this can be enhanced.

**Comment by Aga-C** [comment] 2023-10-13 08:51
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2117.

**Closed** 2023-10-13 16:01 UTC
