### ISSUE TITLE
Banding on both png and jpg

### ISSUE THREAD

**Issue by ShekBoy** [SimpleMobileTools/Simple-Gallery#497] opened 2017-12-13 06:45 UTC
App Version: 3.0.1 from Google Play Store
Device: Sony XZ Premium G8142
OS Version: Android 8.0
Tried PNG and JPG both become the third one shows.
JPG:
![screenshot_20171213-124715](https://user-images.githubusercontent.com/22590886/33923585-ef8ef5d8-e00c-11e7-98b3-ab88f79662bf.jpg)
PNG:
![screenshot_20171213-124715](https://user-images.githubusercontent.com/22590886/33923597-092efa1a-e00d-11e7-8e70-f2106c485876.png)
Both PNG and JPG will become this:
![screenshot_20171213-124654](https://user-images.githubusercontent.com/22590886/33923614-1bab66d8-e00d-11e7-8a0c-58d5796241ec.png)

**Comment by tibbi** [comment] 2017-12-13 08:24
ye Im aware of it, duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/343

**Closed by tibbi** 2017-12-13 08:24 UTC
