### ISSUE TITLE
Weird sorting behavior after updating to 6.12.3

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1737] opened 2020-02-11 01:24 UTC
It's easier to explain with a video.
https://streamable.com/2ug4b
[Attached video zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/4187108/2ug4b.zip)

**Comment by floppyD** [comment] 2020-02-11 02:46
This is also happening, somehow.
https://streamable.com/iypez

**Comment by tibbi** [comment] 2020-02-11 08:44
sorting by last_modified and date_taken is ok, right? Having it in text is a lot better than some videos.

**Comment by floppyD** [comment] 2020-02-11 14:13
Sorting by date taken and last modified should be equivalent when there are no files with EXIF in an album, right? Because that happens in one of my folders, but the thumbnail seems to be randomized when using date taken, it's not the equivalent of any sorting method. And there's that weird sorting that happens sometimes you enter a that folder, that fix itself in a short while (which seems to have that "randomized" album thumbnail as the first pic on the list). Other than that, it seems to be working.

**Comment by floppyD** [comment] 2020-02-11 14:35
Folder with no EXIF
https://streamable.com/1avrx

**Comment by tibbi** [comment] 2020-02-11 15:28
try with 6.12.4 once it becomes available, or get it from github

**Comment by floppyD** [comment] 2020-02-11 16:01
The only thing that seem to have changed is the sorting on the main screen, which actually makes sense now.

**Comment by tibbi** [comment] 2020-02-11 16:23
so what issue is still remaining there?

**Comment by floppyD** [comment] 2020-02-11 16:33
Everything on the first video past 0:34, so main screen thumbnails mismatching the folder contents and the weird sorting that happens sometimes when you open a folder. Also the second video, which seems to be related to the sorting thing.

**Comment by tibbi** [comment] 2020-02-11 16:38
so those issues are only caused by missing Date Taken values? Specify it with text please, I dont like watching videos and thinking what exactly is wrong there. Not to talk about videos that might just disappear anytime.

**Comment by floppyD** [comment] 2020-02-11 16:59
They are all caused by using the Date Taken sorting. On https://github.com/SimpleMobileTools/Simple-Gallery/issues/1737#issuecomment-584664653, I was showing that the Date Taken sorting affects files that don't even have EXIF and that it doesn't use last_modified as fallback in these situations (which seems logical to me), instead sorting by God knows what. About videos, I can attach them in a .zip instead of relying on a third party, if you prefer.

**Comment by tibbi** [comment] 2020-02-11 17:17
okay, Ill see how could it be improved further, or wait for some feedback from other users. Thanks for now

**Comment by Ketrel** [comment] 2020-02-12 03:18
I was having the same sorting issues.  
6.12.4 does appear to resolve the behavior for me.

**Comment by tibbi** [comment] 2020-02-12 15:29
should be fixed in 6.12.5 released soon, hopefully the last release for now. Let me know on hello@simplemobiletools.com if you want a test version. I will release in anyway within a couple hours. Thanks

**Comment by floppyD** [comment] 2020-02-13 18:56
Hi, I tested it and it's really fixed for date taken. There's just one issue, sorting by file size displays the same behavior, with that weird sorting when opening folders and mismatching icons on the main screen. I didn't open another issue since it's still related to sorting issues.

**Comment by tibbi** [comment] 2020-02-13 19:50
you mean that the cover image is not the image which appears first after opening a folder? You use sorting by Size at the files, but what do you use at the main screen sorting?

**Comment by floppyD** [comment] 2020-02-14 00:05
Exactly. I'm using Name and Ascending.

**Comment by tibbi** [comment] 2020-02-14 09:02
hm, I cannot seem to reproduce it. Will see if someone else reports it too.

**Comment by floppyD** [comment] 2020-02-14 13:12
Here
https://streamable.com/2m9x5
[Attached video zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/4204576/2m9x5.zip)

**Comment by tibbi** [comment] 2020-02-14 16:31
ok Ill keep an eye on it, so far nobody reported anything similar

**Comment by floppyD** [comment] 2020-08-11 23:56
I got a new phone running a newer Android version and the problem persists. Also pay attention to the file counter, it's behaving erratically too. Can you re-open this issue?
![4849](https://user-images.githubusercontent.com/29208110/89960315-1603e780-dc15-11ea-85fe-5f6a214489e8.gif)

**Comment by QuickJack** [comment] 2020-10-09 13:37
Sorting by EXIF data is still not working for me. The filenames for photos on my phone are starting with YYYYMMDD_HHMMSS. So this is easy to verify. Sorting by name shows the correct order whereas sorting by "Date taken" shows a very different order. File information shows that "Date taken" is identical to the naming of the file.

**Comment by tibbi** [comment] 2020-10-09 18:32
sorting by date taken is broken in 6.16.1, it will be fixed in the new version released soon

**Comment by QuickJack** [comment] 2020-10-09 18:46
Thanks for the quick response.

09.10.2020 20:32:36 Tibor Kaputa <notifications@github.com>:

**Comment by QuickJack** [comment] 2020-10-20 10:11
It's still not working in 6.16.3.

**Comment by tibbi** [comment] 2020-10-20 10:47
have you used "Fix Date Taken values"?

**Comment by QuickJack** [comment] 2020-10-20 14:20
I can't See this menu. Maybe it's only visible for the English Version?

**Comment by floppyD** [comment] 2020-10-20 15:19
The sort by date taken thing is fixed for me, I just had to select everything and fix date taken.

**Comment by QuickJack** [comment] 2020-10-20 16:32
Yes, the menu appears indeed after selecting individual files. Does this Feature change the image files? What is actually changed and why?
MIUI Gallery displays the same images in the correct order out of the box.

**Comment by tibbi** [comment] 2020-10-21 21:16
Checking file info one by one would be really slow, so at sorting by date taken the values are fetched from an internal database that holds metadata like filename, size, date taken etc. "Fix Date Taken" takes the values from the file itself and updates the values in the database.

**Closed by tibbi** 2020-10-21 21:16 UTC
Labels: bug

**Comment by QuickJack** [comment] 2020-10-21 22:19
> "Fix Date Taken" takes the values from the file itself and updates the values in the database.

OK, I understand. But why are the values in this database wrong? I tried uninstalling/reinstalling which forces the app to create a new database from scratch. After that, sorting is still wrong. So the database is initially filled with wrong values for the field "data taken". This is the actual bug. The new menu entry simply tries to work around this by fixing the database afterwards and with manual intervention.

**Comment by floppyD** [comment] 2020-10-21 23:51
@tibbi The issue described in https://github.com/SimpleMobileTools/Simple-Gallery/issues/1737#issuecomment-672373163 still persists, this new bug was unrelated to the original issue. Could you reopen or should I just open a new issue since some of the problems described here have already been fixed?

**Comment by tibbi** [comment] 2020-10-22 19:21
android works in random ways, hard to say why is something wrong. There are too many device specific setups. Create a new issue please, this is getting messy.

**Comment by QuickJack** [comment] 2021-01-22 13:59
Sorting by date taken is still not working in 6.19.0. The issue has been closed but the bug is still present. Sorting by filename works but this is only a workaround.
