### ISSUE TITLE
[Feature request] webdav

### ISSUE THREAD

**Issue by Sukii23** [SimpleMobileTools/Simple-Gallery#2906] opened 2023-07-23 20:44 UTC
Will the app ever support webdav? it would be awesome to be able to use this gallery app to view the files on your own webdav server.

**Comment by Aga-C** [comment] 2023-07-23 20:57
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/1690.

**Closed** 2023-07-23 21:07 UTC
