### ISSUE TITLE
Option to disable bilinear filtering

### ISSUE THREAD

**Issue by SanJacobs** [SimpleMobileTools/Simple-Gallery#3031] opened 2023-11-03 05:16 UTC
Currently, when viewing small files, like pixel art, and when zooming in, the whole image is blurry.

It should be possible to select "disable bilinear filtering past 250% zoom", or something like that.

Above: Web browser, showing sharp crispy pixels.
![Screenshot_20231103-061503_1.png](https://github.com/SimpleMobileTools/Simple-Gallery/assets/21090839/fda5dbaf-058a-4b12-b86c-5f83a6afa74d)
Below: Simple Gallery, showing blurry obfuscated pixels.

**Comment by Aga-C** [comment] 2023-11-03 06:25
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2902.

**Closed** 2023-11-03 08:55 UTC
