### ISSUE TITLE
Sort by "date taken" does not work 

### ISSUE THREAD

**Issue by Co-7** [SimpleMobileTools/Simple-Gallery#2789] opened 2023-03-05 21:19 UTC
Why was my [issue](https://github.com/SimpleMobileTools/Simple-Gallery/issues/2788#issue-1610283408) closed when the person answered completely wrong? 

Link to my issue here :

https://github.com/SimpleMobileTools/Simple-Gallery/issues/2788#issue-1610283408

**Comment by tibbi** [comment] 2023-03-05 21:21
duplicate of #2788

**Closed by tibbi** 2023-03-05 21:21 UTC
