### ISSUE TITLE
Show xLevel subfolders and do not show (x-1) subfolders

### ISSUE THREAD

**Issue by jorgemarmo** [SimpleMobileTools/Simple-Gallery#976] opened 2018-09-30 16:49 UTC
Hi, great app btw!!
I have a folder called "oldPhoneBkUp" and inside, a ton of subfolders. Now, I would like to see just "oldPhoneBkUp" on the main screen and not all the subfolders. (Of course I would like to see them if I go inside oldPhoneBkUp folder)

**Comment by tibbi** [comment] 2018-09-30 16:57
thanks, but this is a duplicate of #292

**Closed by tibbi** 2018-09-30 16:57 UTC

**Comment by jorgemarmo** [comment] 2018-09-30 17:02
Thanks! 
And sorry for the duplicate...  ;)
