### ISSUE TITLE
Poor image quality for cropped image

### ISSUE THREAD

**Issue by uli-on** [SimpleMobileTools/Simple-Gallery#1744] opened 2020-02-13 14:14 UTC
Currently cropping images leads to very jaggy, rough results, as if a factor 20 compression was chosen or an icon image was used as origin, although I just cut off an edge at one side. (Tested on several JPGs.)

Edit: Best visible on images < 1000 pixels edge length.

App v6.12.5
Android 6.0.1, Moto G4

**Comment by tibbi** [comment] 2020-02-13 16:01
please provide screenshots of before and after views

**Comment by uli-on** [comment] 2020-02-13 17:54
Before
![Screenshot_20200213-170902](https://user-images.githubusercontent.com/35634829/74463344-00924880-4e92-11ea-8534-e575ae8969ff.png)


![Screenshot_20200213-170825](https://user-images.githubusercontent.com/35634829/74463463-2a4b6f80-4e92-11ea-848c-6f8a0fcb98c4.png)
After cropping

**Comment by Ketrel** [comment] 2020-02-19 02:18
I have this happening with jpeg as well.

For an example, here's the source image: https://render-us.worldofwarcraft.com/character/twisting-nether/198/49873606-main.jpg

I tried cropping that down to just the character, and the resulting image had so many artifacts, it was awful.

For some comparison

Left was cropped by another tool, right was cropped with the editor within this app.

https://i.imgur.com/KYJyWHA.jpg

**Comment by uli-on** [comment] 2020-02-19 12:46
The filter tool, too, produces jaggy results, BTW. Hope that makes it easier to spot the error source.

**Comment by tp0** [comment] 2020-02-24 23:15
If #1762 is the same bug then the issue isn't in the filter or crop tool - all tools are affect, or the issue is with the export/save.

**Comment by tibbi** [comment] 2020-02-28 18:41
should be fixed in 6.13.0 released soon

**Closed by tibbi** 2020-02-28 18:41 UTC
Labels: bug

**Comment by lipici** [comment] 2022-05-28 07:07
Still bugged.
