### ISSUE TITLE
Show hidden folder option when moving/copying photos

### ISSUE THREAD

**Issue by leonlywong** [SimpleMobileTools/Simple-Gallery#764] opened 2018-05-02 14:33 UTC
Please add this feature to allow users to show hidden folders while moving/copying.
Although navigating to the hidden folder using "other folder" is workable an alternative
Thanks

**Comment by tibbi** [comment] 2018-05-02 17:03
duplicate of #264

**Closed by tibbi** 2018-05-02 17:03 UTC
