### ISSUE TITLE
Add a button on Thumbnail for preview full screen while selecting multiple photos

### ISSUE THREAD

**Issue by souravdas142** [SimpleMobileTools/Simple-Gallery#2268] opened 2021-11-20 11:30 UTC
Hii @tibbi  Thanks for creating This. This issue extends https://github.com/SimpleMobileTools/Simple-Gallery/issues/1952  with more explanation.

This option we are asked here is actually inspired from Samsung Gallery app. Below is the screenshot. 

![SamsungGalary_SelectionPreview](https://user-images.githubusercontent.com/24272753/142724096-660b01ef-30ea-44e5-b75b-c6023b5a08f7.jpeg)

Its a long time feature-request we are asking because of while selecting photos sometime we are undetermined whether should we select this photo or that for further action and we got confused right ? In that situation if Suppose we had choose a thousand photo already then there are no other option left unselecting all of them to determine that photo whether should we choose it or not by viewing it in full screen right ? But If you give a preview or a view button on thumbnail like what shown in above screenshot, We can preview them and select it  without unselecting previously selected photo right ? And obviously a thumbnail does not hold lot of detail to choose similar photos right ? It Will be very productive and a lot of time saver. 
    Considering This can you please work on it to add a preview button the same like above screenshot ? Thank you by the way.

**Comment by tibbi** [comment] 2021-11-20 17:45
duplicate of #1952

**Closed by tibbi** 2021-11-20 17:45 UTC
