### ISSUE TITLE
All EXIF data deleted automatically when cropping or rotating

### ISSUE THREAD

**Issue by zilexa** [SimpleMobileTools/Simple-Gallery#2858] opened 2023-05-29 19:19 UTC
As discussed here:
https://www.reddit.com/r/SimpleMobileTools/comments/13rx18q/exif_date_taken_deleted_after_cropping/

Using Simple Gallery Pro 6.28.6, take a photo, check all EXIF info like date taken, GPS, camera sensor info.

Then crop the photo a little. Notice now all EXIF data is gone. 

Since I crop and save with the exact same name because I have no need for the original, this info is now lost forever.

**Comment by tibbi** [comment] 2023-05-29 19:22
what OS version are you using? Have you granted the app All Files access?

**Comment by Aga-C** [comment] 2023-05-30 04:34
Despite giving All Files access, it doesn't work. It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2189.

**Closed** 2023-05-30 06:38 UTC
